// This file is auto-generated by generateFeatureRoutes.js. Do not edit directly.

import charactersRouter from '../features/characters/routes/charactersRoutes.js';
import classesRouter from '../features/classes/routes/classesRoutes.js';
import featsRouter from '../features/feats/routes/featsRoutes.js';
import racesRouter from '../features/races/routes/racesRoutes.js';
import referencetablesRouter from '../features/referencetables/routes/referencetablesRoutes.js';
import skillsRouter from '../features/skills/routes/skillsRoutes.js';
import spellsRouter from '../features/spells/routes/spellsRoutes.js';

export const featureRoutes = [
    { path: '/api/characters', router: charactersRouter },
    { path: '/api/classes', router: classesRouter },
    { path: '/api/feats', router: featsRouter },
    { path: '/api/races', router: racesRouter },
    { path: '/api/referencetables', router: referencetablesRouter },
    { path: '/api/skills', router: skillsRouter },
    { path: '/api/spells', router: spellsRouter },
];
