import { ClassMap } from './types';

export const CLASS_MAP: ClassMap = {
    1: { id: 1, name: 'Barbarian', abbr: 'Bbn', edition_id: 4, display: 0, can_cast: 0, is_prestige: 0 },
    2: { id: 2, name: 'Bard', abbr: 'Brd', edition_id: 4, display: 0, can_cast: 1, is_prestige: 0 },
    3: { id: 3, name: 'Cleric', abbr: 'Clr', edition_id: 4, display: 0, can_cast: 1, is_prestige: 0 },
    4: { id: 4, name: 'Druid', abbr: 'Drd', edition_id: 4, display: 0, can_cast: 1, is_prestige: 0 },
    5: { id: 5, name: 'Fighter', abbr: 'Ftr', edition_id: 4, display: 0, can_cast: 0, is_prestige: 0 },
    6: { id: 6, name: 'Monk', abbr: 'Mnk', edition_id: 4, display: 0, can_cast: 0, is_prestige: 0 },
    7: { id: 7, name: 'Paladin', abbr: 'Pal', edition_id: 4, display: 0, can_cast: 1, is_prestige: 0 },
    8: { id: 8, name: 'Ranger', abbr: 'Rgr', edition_id: 4, display: 0, can_cast: 1, is_prestige: 0 },
    9: { id: 9, name: 'Rogue', abbr: 'Rog', edition_id: 4, display: 0, can_cast: 0, is_prestige: 0 },
    10: { id: 10, name: 'Sorcerer', abbr: 'Sor', edition_id: 4, display: 0, can_cast: 1, is_prestige: 0 },
    11: { id: 11, name: 'Wizard', abbr: 'Wiz', edition_id: 4, display: 0, can_cast: 1, is_prestige: 0 },
    12: { id: 12, name: 'Adept', abbr: 'Adpt', edition_id: 4, display: 1, can_cast: 1, is_prestige: 0 },
    13: { id: 13, name: 'Aristocrat', abbr: 'Arist', edition_id: 4, display: 1, can_cast: 0, is_prestige: 0 },
    14: { id: 14, name: 'Commoner', abbr: 'Cmn', edition_id: 4, display: 1, can_cast: 0, is_prestige: 0 },
    15: { id: 15, name: 'Expert', abbr: 'Exp', edition_id: 4, display: 1, can_cast: 0, is_prestige: 0 },
    16: { id: 16, name: 'Warrior', abbr: 'War', edition_id: 4, display: 1, can_cast: 0, is_prestige: 0 },
    17: { id: 17, name: 'Barbarian', abbr: 'Bbn', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    18: { id: 18, name: 'Bard', abbr: 'Brd', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    19: { id: 19, name: 'Cleric', abbr: 'Clr', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    20: { id: 20, name: 'Druid', abbr: 'Drd', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    21: { id: 21, name: 'Fighter', abbr: 'Ftr', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    22: { id: 22, name: 'Monk', abbr: 'Mnk', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    23: { id: 23, name: 'Paladin', abbr: 'Pal', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    24: { id: 24, name: 'Ranger', abbr: 'Rgr', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    25: { id: 25, name: 'Rogue', abbr: 'Rog', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    26: { id: 26, name: 'Sorcerer', abbr: 'Sor', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    27: { id: 27, name: 'Wizard', abbr: 'Wiz', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    28: { id: 28, name: 'Hexblade', abbr: 'Hex', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    29: { id: 29, name: 'Samurai', abbr: 'Sam', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    30: { id: 30, name: 'Swashbuckler', abbr: 'Swb', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    31: { id: 31, name: 'Scout', abbr: 'Sct', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    32: { id: 32, name: 'Ninja', abbr: 'Nin', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    33: { id: 33, name: 'Spellthief', abbr: 'Sth', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    34: { id: 34, name: 'Warlock', abbr: 'Wlk', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    35: { id: 35, name: 'Warmage', abbr: 'Wmg', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    36: { id: 36, name: 'Wu Jen', abbr: 'Wuj', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    37: { id: 37, name: 'Favored Soul', abbr: 'Fvs', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    38: { id: 38, name: 'Shugenja', abbr: 'Shug', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    39: { id: 39, name: 'Spirit Shaman', abbr: 'Ssh', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    40: { id: 40, name: 'Psion', abbr: 'Psi', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    41: { id: 41, name: 'Psychic Warrior', abbr: 'PsyW', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    42: { id: 42, name: 'Soulknife', abbr: 'Skn', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    43: { id: 43, name: 'Wilder', abbr: 'Wld', edition_id: 5, display: 1, can_cast: 0, is_prestige: 0 },
    44: { id: 44, name: 'Arcane Archer', abbr: 'AA', edition_id: 4, display: 1, can_cast: 0, is_prestige: 1 },
    45: { id: 45, name: 'Arcane Trickster', abbr: 'AT', edition_id: 4, display: 1, can_cast: 0, is_prestige: 1 },
    46: { id: 46, name: 'Archmage', abbr: 'Arch', edition_id: 4, display: 1, can_cast: 0, is_prestige: 1 },
    47: { id: 47, name: 'Assassin', abbr: 'Asn', edition_id: 4, display: 1, can_cast: 1, is_prestige: 1 },
    48: { id: 48, name: 'Blackguard', abbr: 'Bg', edition_id: 4, display: 1, can_cast: 1, is_prestige: 1 },
    49: { id: 49, name: 'Dragon Disciple', abbr: 'DD', edition_id: 4, display: 1, can_cast: 0, is_prestige: 1 },
    50: { id: 50, name: 'Duelist', abbr: 'Duel', edition_id: 4, display: 1, can_cast: 0, is_prestige: 1 },
    51: { id: 51, name: 'Dwarven Defender', abbr: 'DDf', edition_id: 4, display: 1, can_cast: 0, is_prestige: 1 },
    52: { id: 52, name: 'Eldritch Knight', abbr: 'EK', edition_id: 4, display: 1, can_cast: 0, is_prestige: 1 },
    53: { id: 53, name: 'Loremaster', abbr: 'LM', edition_id: 4, display: 1, can_cast: 0, is_prestige: 1 },
    54: { id: 54, name: 'Mystic Theurge', abbr: 'MT', edition_id: 4, display: 1, can_cast: 0, is_prestige: 1 },
    55: { id: 55, name: 'Shadowdancer', abbr: 'SD', edition_id: 4, display: 1, can_cast: 0, is_prestige: 1 },
    56: { id: 56, name: 'Arcane Archer', abbr: 'AA', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    57: { id: 57, name: 'Arcane Trickster', abbr: 'AT', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    58: { id: 58, name: 'Archmage', abbr: 'Arch', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    59: { id: 59, name: 'Assassin', abbr: 'Asn', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    60: { id: 60, name: 'Blackguard', abbr: 'Bg', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    61: { id: 61, name: 'Dragon Disciple', abbr: 'DD', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    62: { id: 62, name: 'Duelist', abbr: 'Duel', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    63: { id: 63, name: 'Dwarven Defender', abbr: 'DDf', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    64: { id: 64, name: 'Eldritch Knight', abbr: 'EK', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    65: { id: 65, name: 'Loremaster', abbr: 'LM', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    66: { id: 66, name: 'Mystic Theurge', abbr: 'MT', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    67: { id: 67, name: 'Shadowdancer', abbr: 'SD', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    68: { id: 68, name: 'Bladesinger', abbr: 'Bls', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    69: { id: 69, name: 'Spellsword', abbr: 'Ssw', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    70: { id: 70, name: 'Weapon Master', abbr: 'WM', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    71: { id: 71, name: 'Arcane Hierophant', abbr: 'AH', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    72: { id: 72, name: 'Fochlucan Lyrist', abbr: 'FL', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    73: { id: 73, name: 'Daggerspell Mage', abbr: 'DM', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    74: { id: 74, name: 'Daggerspell Shaper', abbr: 'DS', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    75: { id: 75, name: 'Nightsong Enforcer', abbr: 'NE', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    76: { id: 76, name: 'Nightsong Infiltrator', abbr: 'NI', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    77: { id: 77, name: 'Beastmaster', abbr: 'BM', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    78: { id: 78, name: 'Exemplar', abbr: 'Ex', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    79: { id: 79, name: 'Ollam', abbr: 'Ol', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    80: { id: 80, name: 'Maester', abbr: 'Ma', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    81: { id: 81, name: 'Tempest', abbr: 'Tp', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    82: { id: 82, name: 'Wild Plains Outrider', abbr: 'WPO', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    83: { id: 83, name: 'Bloodhound', abbr: 'Bh', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    84: { id: 84, name: 'Vigilante', abbr: 'Vig', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    85: { id: 85, name: 'Acolyte of the Skin', abbr: 'ASk', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    86: { id: 86, name: 'Alienist', abbr: 'Aln', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    87: { id: 87, name: 'Argent Savant', abbr: 'ASv', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    88: { id: 88, name: 'Geomancer', abbr: 'Geo', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    89: { id: 89, name: 'Contemplative', abbr: 'Cmp', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    90: { id: 90, name: 'Divine Oracle', abbr: 'DO', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    91: { id: 91, name: 'Sacred Fist', abbr: 'SF', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    92: { id: 92, name: 'Seeker of the Misty Isle', abbr: 'SMI', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    93: { id: 93, name: 'Thaumaturgist', abbr: 'Thm', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    94: { id: 94, name: 'Anointed Knight', abbr: 'AK', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    95: { id: 95, name: 'Exalted Arcanist', abbr: 'EA', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    96: { id: 96, name: 'Fist of Raziel', abbr: 'FR', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    97: { id: 97, name: 'Justiciar of Tyr', abbr: 'JT', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    98: { id: 98, name: 'Lion of Talisid', abbr: 'LT', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    99: { id: 99, name: 'Slayer of Domiel', abbr: 'SDm', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    100: { id: 100, name: 'Stalker of Kharash', abbr: 'SK', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    101: { id: 101, name: 'Vassal of Bahamut', abbr: 'VB', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    102: { id: 102, name: 'Apostle of Peace', abbr: 'AoP', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    103: { id: 103, name: 'Archivist', abbr: 'Archv', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    104: { id: 104, name: 'Artificer', abbr: 'Arti', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    105: { id: 105, name: 'Beguiler', abbr: 'Begl', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    106: { id: 106, name: 'Beloved of Valarian', abbr: 'BoV', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    107: { id: 107, name: 'Blighter', abbr: 'Blght', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    108: { id: 108, name: 'Champion of Gwynharwyf', abbr: 'CoG', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    109: { id: 109, name: 'Consecrated Harrier', abbr: 'ConHar', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    110: { id: 110, name: 'Corrupt Avenger', abbr: 'CorAv', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    111: { id: 111, name: 'Death Delver', abbr: 'DthDel', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    112: { id: 112, name: 'Demonologist', abbr: 'Dmn', edition_id: 4, display: 1, can_cast: 1, is_prestige: 1 },
    113: { id: 113, name: 'Disciple of Thrym', abbr: 'DoT', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    114: { id: 114, name: 'Divine Crusader', abbr: 'DivCru', edition_id: 5, display: 1, can_cast: 0, is_prestige: 1 },
    115: { id: 115, name: 'Dread Necromancer', abbr: 'DrdNec', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    116: { id: 116, name: 'Duskblade', abbr: 'DskBl', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    117: { id: 117, name: 'Emissary of Barachiel', abbr: 'EoB', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    118: { id: 118, name: 'Fatemaker', abbr: 'Ftmk', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    119: { id: 119, name: 'Gnome Artificer', abbr: 'GnArt', edition_id: 4, display: 1, can_cast: 1, is_prestige: 1 },
    120: { id: 120, name: 'Healer', abbr: 'Heal', edition_id: 5, display: 1, can_cast: 1, is_prestige: 0 },
    121: { id: 121, name: 'Hoardstealer', abbr: 'HrdStl', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    122: { id: 122, name: 'Holy Liberator', abbr: 'HoLib', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    123: { id: 123, name: 'Hunter of the Dead', abbr: 'HotD', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    124: { id: 124, name: 'Knight of the Chalice', abbr: 'KotC', edition_id: 4, display: 1, can_cast: 1, is_prestige: 1 },
    125: { id: 125, name: 'Mortal Hunter', abbr: 'MrtHnt', edition_id: 4, display: 1, can_cast: 1, is_prestige: 1 },
    126: { id: 126, name: 'Ocular Adept', abbr: 'OcAdp', edition_id: 4, display: 1, can_cast: 1, is_prestige: 1 },
    127: { id: 127, name: 'Pious Templar', abbr: 'PiTem', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    128: { id: 128, name: 'Sublime Chord', abbr: 'SubCh', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    129: { id: 129, name: 'Suel Arcanamach', abbr: 'SlArcan', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    130: { id: 130, name: 'Temple Raider of Olidammara', abbr: 'TRoO', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
    131: { id: 131, name: 'Ur-Priest', abbr: 'UrPrst', edition_id: 5, display: 1, can_cast: 1, is_prestige: 1 },
};

export const CLASS_LIST = Object.values(CLASS_MAP);

export function GetBaseClassesByEdition(editionId: number) {
    return CLASS_LIST.filter(cl => cl.edition_id === editionId && !cl.is_prestige);
} 