import { Setting, EditionId } from './CommonData';
import type { SourceBookMap, SourceBookData } from './types';

export const SourceBook = {
    PlayersHandbook_3_0: 1,
    SunlessCitadel: 2,
    DungeonMastersGuide_3_0: 3,
    DungeonsAndDragonsGazeteer: 4,
    MonsterManual_3_0: 5,
    ForgeOfFury: 6,
    HeroBuildersGuidebook: 7,
    SpeakerInDreams: 8,
    SwordAndFist: 9,
    MonstersOfFaerun: 10,
    PsionicsHandbook: 11,
    StandingStone: 12,
    DefendersOfTheFaith: 13,
    ForgottenRealmsCampaignSetting: 14,
    ReturnToTheTempleOfElementalEvil: 15,
    HeartOfNightfangSpire: 16,
    TomeAndBlood: 17,
    MagicOfFaerun: 18,
    ManualOfThePlanes: 19,
    EnemiesAndAllies: 20,
    OrientalAdventures: 21,
    DeepHorizon: 22,
    LordsOfDarkness: 23,
    SongAndSilence: 24,
    LordOfTheIronFortress: 25,
    MastersOfTheWild: 26,
    BastionOfBrokenSouls: 27,
    DeitiesAndDemigods: 28,
    FaithsAndPantheons: 29,
    StrongholdBuildersGuidebook: 30,
    BookOfChallenges: 31,
    EpicLevelHandbook: 32,
    SilverMarches: 33,
    CityOfTheSpiderQueen: 34,
    MonsterManualII: 35,
    BookOfVileDarkness: 36,
    SavageSpecies: 37,
    ArmsAndEquipmentGuide: 38,
    RacesOfFaerun: 39,
    FiendFolio: 40,
    UnapproachableEast: 41,
    Ghostwalk: 42,
    DungeonMastersGuide_3_5: 43,
    MonsterManual_3_5: 44,
    PlayersHandbook_3_5: 45,
    DragonlanceCampaignSetting: 46,
    MiniaturesHandbook: 47,
    BookOfExaltedDeeds: 48,
    Underdark: 49,
    Draconomicon: 50,
    CompleteWarrior: 51,
    UnearthedArcana: 52,
    PlayerGuideToFaerun: 53,
    ExpandedPsionicsHandbook: 54,
    CompleteDivine: 55,
    EberronCampaignSetting: 56,
    PlanarHandbook: 57,
    SerpentKingdoms: 58,
    ShadowsOfTheLastWar: 59,
    RacesOfStone: 60,
    Frostburn: 61,
    MonsterManualIII: 62,
    LibrisMortis: 63,
    ShiningSouth: 64,
    WhispersOfTheVampiresBlade: 65,
    CompleteArcane: 66,
    SharnCityOfTowers: 67,
    RacesOfDestiny: 68,
    CompleteAdventurer: 69,
    GraspOfTheEmeraldClaw: 70,
    LostEmpiresOfFaerun: 71,
    RacesOfTheWild: 72,
    Sandstorm: 73,
    LordsOfMadness: 74,
    RacesOfEberron: 75,
    ChampionsOfRuin: 76,
    HeroesOfBattle: 77,
    CityOfSplendorsWaterdeep: 78,
    DungeonMastersGuideII: 79,
    FiveNations: 80,
    WeaponsOfLegacy: 81,
    ExplorersHandbook: 82,
    Stormwrack: 83,
    FantasticLocationsFaneOfTheDrow: 84,
    MagicOfIncarnum: 85,
    SonsOfGruumsh: 86,
    HeroesOfHorror: 87,
    MagicOfEberron: 88,
    ChampionsOfValor: 89,
    FantasticLocationsHellspikePrison: 90,
    SpellCompendium: 91,
    PlayersGuideToEberron: 92,
    RacesOfTheDragon: 93,
    RedHandOfDoom: 94,
    PowerOfFaerun: 95,
    TomeOfMagic: 96,
    CompletePsionic: 97,
    FantasticLocationsFieldsOfRuin: 98,
    VoyageOfTheGoldenDragon: 99,
    PlayersHandbookII: 100,
    FiendishCodexI: 101,
    MysteriesOfTheMoonsea: 102,
    FantasticLocationsDragondownGrotto: 103,
    MonsterManualIV: 104,
    SecretsOfXendrik: 105,
    DragonsOfFaerun: 106,
    TomeOfBattle: 107,
    DragonMagic: 108,
    FaithsOfEberron: 109,
    TwilightTomb: 110,
    CompleteMage: 111,
    ExpeditionToCastleRavenloft: 112,
    Cityscape: 113,
    Dragonmarked: 114,
    ScourgeOfTheHowlingHorde: 115,
    AnimatedSeriesHandbook: 116,
    FantasticLocationsTheFrostfellRift: 117,
    FiendishCodexII: 118,
    ShatteredGatesOfSlaughtergarde: 119,
    CompleteScoundrel: 120,
    BarrowOfTheForgottenKing: 121,
    Dungeonscape: 122,
    SecretsOfSarlona: 123,
    MagicItemCompendium: 124,
    CormyrTheTearingOfTheWeave: 125,
    EyesOfTheLichQueen: 126,
    ExpeditionToTheDemonwebPits: 127,
    FantasticLocationsCityInPeril: 128,
    CompleteChampion: 129,
    DrowOfTheUnderdark: 130,
    ExpeditionToUndermountain: 131,
    ForgeOfWar: 132,
    SinisterSpire: 133,
    MonsterManualV: 134,
    ShadowdaleTheScouringOfTheLand: 135,
    ExpeditionToTheRuinsOfGreyhawk: 136,
    ExemplarsOfEvil: 137,
    FortressOfTheYuanTi: 138,
    GrandHistoryOfTheRealms: 139,
    DragonsOfEberron: 140,
    RulesCompendium: 141,
    AnaurochTheEmpireOfShade: 142,
    ElderEvils: 143,
    CityOfStormreach: 144,
    AnAdventurersGuideToEberron: 145,
} as const;

export type SourceBook = typeof SourceBook[keyof typeof SourceBook];

export const SOURCE_BOOK_MAP: SourceBookMap = {
    [SourceBook.PlayersHandbook_3_0]: { id: 1, name: "Player's Handbook", abbreviation: 'PHB', editionId: EditionId.DND_3E, isVisible: false },
    [SourceBook.SunlessCitadel]: { id: 2, name: 'Sunless Citadel', abbreviation: 'SC', editionId: EditionId.DND_3E },
    [SourceBook.DungeonMastersGuide_3_0]: { id: 3, name: "Dungeon Master's Guide", abbreviation: 'DMG', editionId: EditionId.DND_3E, isVisible: false },
    [SourceBook.DungeonsAndDragonsGazeteer]: { id: 4, name: 'Dungeons and Dragons Gazeteer', abbreviation: 'DDG', editionId: EditionId.DND_3E, },
    [SourceBook.MonsterManual_3_0]: { id: 5, name: 'Monster Manual', abbreviation: 'MM', editionId: EditionId.DND_3E, isVisible: false },
    [SourceBook.ForgeOfFury]: { id: 6, name: 'Forge of Fury', abbreviation: 'FoF', editionId: EditionId.DND_3E },
    [SourceBook.HeroBuildersGuidebook]: { id: 7, name: "Hero Builder's Guidebook", abbreviation: 'HBG', editionId: EditionId.DND_3E },
    [SourceBook.SpeakerInDreams]: { id: 8, name: 'Speaker in Dreams', abbreviation: 'SiD', editionId: EditionId.DND_3E },
    [SourceBook.SwordAndFist]: { id: 9, name: 'Sword and Fist', abbreviation: 'SaF', editionId: EditionId.DND_3E },
    [SourceBook.MonstersOfFaerun]: { id: 10, name: 'Monsters of Faerûn', abbreviation: 'MoF', editionId: EditionId.DND_3E },
    [SourceBook.PsionicsHandbook]: { id: 11, name: 'Psionics Handbook', abbreviation: 'PsH', editionId: EditionId.DND_3E },
    [SourceBook.StandingStone]: { id: 12, name: 'Standing Stone', abbreviation: 'StS', editionId: EditionId.DND_3E },
    [SourceBook.DefendersOfTheFaith]: { id: 13, name: 'Defenders of the Faith', abbreviation: 'DotF', editionId: EditionId.DND_3E },
    [SourceBook.ForgottenRealmsCampaignSetting]: { id: 14, name: 'Forgotten Realms Campaign Setting', abbreviation: 'FRCS', editionId: EditionId.DND_3E },
    [SourceBook.ReturnToTheTempleOfElementalEvil]: { id: 15, name: 'Return to the Temple of Elemental Evil', abbreviation: 'RToEE', editionId: EditionId.DND_3E },
    [SourceBook.HeartOfNightfangSpire]: { id: 16, name: 'Heart of Nightfang Spire', abbreviation: 'HoNS', editionId: EditionId.DND_3E },
    [SourceBook.TomeAndBlood]: { id: 17, name: 'Tome and Blood', abbreviation: 'TaB', editionId: EditionId.DND_3E },
    [SourceBook.MagicOfFaerun]: { id: 18, name: 'Magic of Faerûn', abbreviation: 'MagF', editionId: EditionId.DND_3E },
    [SourceBook.ManualOfThePlanes]: { id: 19, name: 'Manual of the Planes', abbreviation: 'MotP', editionId: EditionId.DND_3E },
    [SourceBook.EnemiesAndAllies]: { id: 20, name: 'Enemies and Allies', abbreviation: 'EA', editionId: EditionId.DND_3E },
    [SourceBook.OrientalAdventures]: { id: 21, name: 'Oriental Adventures', abbreviation: 'OA', editionId: EditionId.DND_3E },
    [SourceBook.DeepHorizon]: { id: 22, name: 'Deep Horizon', abbreviation: 'DH', editionId: EditionId.DND_3E },
    [SourceBook.LordsOfDarkness]: { id: 23, name: 'Lords of Darkness', abbreviation: 'LD', editionId: EditionId.DND_3E },
    [SourceBook.SongAndSilence]: { id: 24, name: 'Song and Silence', abbreviation: 'SaS', editionId: EditionId.DND_3E },
    [SourceBook.LordOfTheIronFortress]: { id: 25, name: 'Lord of the Iron Fortress', abbreviation: 'LotIF', editionId: EditionId.DND_3E },
    [SourceBook.MastersOfTheWild]: { id: 26, name: 'Masters of the Wild', abbreviation: 'MotW', editionId: EditionId.DND_3E },
    [SourceBook.BastionOfBrokenSouls]: { id: 27, name: 'Bastion of Broken Souls', abbreviation: 'BoBS', editionId: EditionId.DND_3E },
    [SourceBook.DeitiesAndDemigods]: { id: 28, name: 'Deities and Demigods', abbreviation: 'DD', editionId: EditionId.DND_3E },
    [SourceBook.FaithsAndPantheons]: { id: 29, name: 'Faiths and Pantheons', abbreviation: 'FP', editionId: EditionId.DND_3E },
    [SourceBook.StrongholdBuildersGuidebook]: { id: 30, name: "Stronghold Builder's Guidebook", abbreviation: 'SBG', editionId: EditionId.DND_3E },
    [SourceBook.BookOfChallenges]: { id: 31, name: 'Book of Challenges', abbreviation: 'BoC', editionId: EditionId.DND_3E },
    [SourceBook.EpicLevelHandbook]: { id: 32, name: 'Epic Level Handbook', abbreviation: 'EL', editionId: EditionId.DND_3E },
    [SourceBook.SilverMarches]: { id: 33, name: 'Silver Marches', abbreviation: 'SM', editionId: EditionId.DND_3E },
    [SourceBook.CityOfTheSpiderQueen]: { id: 34, name: 'City of the Spider Queen', abbreviation: 'CSQ', editionId: EditionId.DND_3E },
    [SourceBook.MonsterManualII]: { id: 35, name: 'Monster Manual II', abbreviation: 'MM2', editionId: EditionId.DND_3E, },
    [SourceBook.BookOfVileDarkness]: { id: 36, name: 'Book of Vile Darkness', abbreviation: 'BoVD', editionId: EditionId.DND_3E },
    [SourceBook.SavageSpecies]: { id: 37, name: 'Savage Species', abbreviation: 'SS', editionId: EditionId.DND_3E },
    [SourceBook.ArmsAndEquipmentGuide]: { id: 38, name: 'Arms and Equipment Guide', abbreviation: 'AEG', editionId: EditionId.DND_3E, },
    [SourceBook.RacesOfFaerun]: { id: 39, name: 'Races of Faerûn', abbreviation: 'RacF', editionId: EditionId.DND_3E },
    [SourceBook.FiendFolio]: { id: 40, name: 'Fiend Folio', abbreviation: 'FF', editionId: EditionId.DND_3E },
    [SourceBook.UnapproachableEast]: { id: 41, name: 'Unapproachable East', abbreviation: 'UnaE', editionId: EditionId.DND_3E },
    [SourceBook.Ghostwalk]: { id: 42, name: 'Ghostwalk', abbreviation: 'GhW', editionId: EditionId.DND_3E },
    [SourceBook.DungeonMastersGuide_3_5]: { id: 43, name: "Dungeon Master's Guide", abbreviation: 'DMG', editionId: EditionId.DND_3_5E, },
    [SourceBook.MonsterManual_3_5]: { id: 44, name: 'Monster Manual', abbreviation: 'MM', editionId: EditionId.DND_3_5E },
    [SourceBook.PlayersHandbook_3_5]: { id: 45, name: "Player's Handbook", abbreviation: 'PHB', editionId: EditionId.DND_3_5E },
    [SourceBook.DragonlanceCampaignSetting]: { id: 46, name: 'Dragonlance Campaign Setting', abbreviation: 'DCS', editionId: EditionId.DND_3_5E },
    [SourceBook.MiniaturesHandbook]: { id: 47, name: 'Miniatures Handbook', abbreviation: 'MH', editionId: EditionId.DND_3_5E },
    [SourceBook.BookOfExaltedDeeds]: { id: 48, name: 'Book of Exalted Deeds', abbreviation: 'BoED', editionId: EditionId.DND_3_5E },
    [SourceBook.Underdark]: { id: 49, name: 'Underdark', abbreviation: 'Und', editionId: EditionId.DND_3_5E },
    [SourceBook.Draconomicon]: { id: 50, name: 'Draconomicon', abbreviation: 'Dr', editionId: EditionId.DND_3_5E },
    [SourceBook.CompleteWarrior]: { id: 51, name: 'Complete Warrior', abbreviation: 'CW', editionId: EditionId.DND_3_5E },
    [SourceBook.UnearthedArcana]: { id: 52, name: 'Unearthed Arcana', abbreviation: 'UA', editionId: EditionId.DND_3_5E },
    [SourceBook.PlayerGuideToFaerun]: { id: 53, name: "Player's Guide to Faerûn", abbreviation: 'PG', editionId: EditionId.DND_3_5E },
    [SourceBook.ExpandedPsionicsHandbook]: { id: 54, name: 'Expanded Psionics Handbook', abbreviation: 'XPH', editionId: EditionId.DND_3_5E },
    [SourceBook.CompleteDivine]: { id: 55, name: 'Complete Divine', abbreviation: 'CD', editionId: EditionId.DND_3_5E },
    [SourceBook.EberronCampaignSetting]: { id: 56, name: 'Eberron Campaign Setting', abbreviation: 'ECS', editionId: EditionId.DND_3_5E },
    [SourceBook.PlanarHandbook]: { id: 57, name: 'Planar Handbook', abbreviation: 'PlH', editionId: EditionId.DND_3_5E },
    [SourceBook.SerpentKingdoms]: { id: 58, name: 'Serpent Kingdoms', abbreviation: 'SK', editionId: EditionId.DND_3_5E },
    [SourceBook.ShadowsOfTheLastWar]: { id: 59, name: 'Shadows of the Last War', abbreviation: 'SL', editionId: EditionId.DND_3_5E },
    [SourceBook.RacesOfStone]: { id: 60, name: 'Races of Stone', abbreviation: 'RS', editionId: EditionId.DND_3_5E },
    [SourceBook.Frostburn]: { id: 61, name: 'Frostburn', abbreviation: 'Fr', editionId: EditionId.DND_3_5E },
    [SourceBook.MonsterManualIII]: { id: 62, name: 'Monster Manual III', abbreviation: 'MM3', editionId: EditionId.DND_3_5E },
    [SourceBook.LibrisMortis]: { id: 63, name: 'Libris Mortis', abbreviation: 'LM', editionId: EditionId.DND_3_5E },
    [SourceBook.ShiningSouth]: { id: 64, name: 'Shining South', abbreviation: 'ShS', editionId: EditionId.DND_3_5E },
    [SourceBook.WhispersOfTheVampiresBlade]: { id: 65, name: "Whispers of the Vampire's Blade", abbreviation: 'WB', editionId: EditionId.DND_3_5E },
    [SourceBook.CompleteArcane]: { id: 66, name: 'Complete Arcane', abbreviation: 'CAr', editionId: EditionId.DND_3_5E },
    [SourceBook.SharnCityOfTowers]: { id: 67, name: 'Sharn: City of Towers', abbreviation: 'Sh', editionId: EditionId.DND_3_5E },
    [SourceBook.RacesOfDestiny]: { id: 68, name: 'Races of Destiny', abbreviation: 'RD', editionId: EditionId.DND_3_5E },
    [SourceBook.CompleteAdventurer]: { id: 69, name: 'Complete Adventurer', abbreviation: 'CAd', editionId: EditionId.DND_3_5E },
    [SourceBook.GraspOfTheEmeraldClaw]: { id: 70, name: 'Grasp of the Emerald Claw', abbreviation: 'GC', editionId: EditionId.DND_3_5E },
    [SourceBook.LostEmpiresOfFaerun]: { id: 71, name: 'Lost Empires of Faerûn', abbreviation: 'LE', editionId: EditionId.DND_3_5E },
    [SourceBook.RacesOfTheWild]: { id: 72, name: 'Races of the Wild', abbreviation: 'RW', editionId: EditionId.DND_3_5E },
    [SourceBook.Sandstorm]: { id: 73, name: 'Sandstorm', abbreviation: 'Sa', editionId: EditionId.DND_3_5E },
    [SourceBook.LordsOfMadness]: { id: 74, name: 'Lords of Madness', abbreviation: 'LoM', editionId: EditionId.DND_3_5E },
    [SourceBook.RacesOfEberron]: { id: 75, name: 'Races of Eberron', abbreviation: 'RE', editionId: EditionId.DND_3_5E },
    [SourceBook.ChampionsOfRuin]: { id: 76, name: 'Champions of Ruin', abbreviation: 'CR', editionId: EditionId.DND_3_5E },
    [SourceBook.HeroesOfBattle]: { id: 77, name: 'Heroes of Battle', abbreviation: 'HB', editionId: EditionId.DND_3_5E },
    [SourceBook.CityOfSplendorsWaterdeep]: { id: 78, name: 'City of Splendors: Waterdeep', abbreviation: 'CSW', editionId: EditionId.DND_3_5E },
    [SourceBook.DungeonMastersGuideII]: { id: 79, name: "Dungeon Master's Guide II", abbreviation: 'DMG2', editionId: EditionId.DND_3_5E },
    [SourceBook.FiveNations]: { id: 80, name: 'Five Nations', abbreviation: 'FN', editionId: EditionId.DND_3_5E },
    [SourceBook.WeaponsOfLegacy]: { id: 81, name: 'Weapons of Legacy', abbreviation: 'WL', editionId: EditionId.DND_3_5E },
    [SourceBook.ExplorersHandbook]: { id: 82, name: "Explorer's Handbook", abbreviation: 'EH', editionId: EditionId.DND_3_5E },
    [SourceBook.Stormwrack]: { id: 83, name: 'Stormwrack', abbreviation: 'Sto', editionId: EditionId.DND_3_5E, },
    [SourceBook.FantasticLocationsFaneOfTheDrow]: { id: 84, name: 'Fantastic Locations: Fane of the Drow', abbreviation: 'FLFD', editionId: EditionId.DND_3_5E },
    [SourceBook.MagicOfIncarnum]: { id: 85, name: 'Magic of Incarnum', abbreviation: 'MoI', editionId: EditionId.DND_3_5E },
    [SourceBook.SonsOfGruumsh]: { id: 86, name: 'Sons of Gruumsh', abbreviation: 'SG', editionId: EditionId.DND_3_5E },
    [SourceBook.HeroesOfHorror]: { id: 87, name: 'Heroes of Horror', abbreviation: 'HH', editionId: EditionId.DND_3_5E },
    [SourceBook.MagicOfEberron]: { id: 88, name: 'Magic of Eberron', abbreviation: 'MoE', editionId: EditionId.DND_3_5E },
    [SourceBook.ChampionsOfValor]: { id: 89, name: 'Champions of Valor', abbreviation: 'CV', editionId: EditionId.DND_3_5E },
    [SourceBook.FantasticLocationsHellspikePrison]: { id: 90, name: 'Fantastic Locations: Hellspike Prison', abbreviation: 'FLHP', editionId: EditionId.DND_3_5E },
    [SourceBook.SpellCompendium]: { id: 91, name: 'Spell Compendium', abbreviation: 'SpC', editionId: EditionId.DND_3_5E },
    [SourceBook.PlayersGuideToEberron]: { id: 92, name: "Player's Guide to Eberron", abbreviation: 'PE', editionId: EditionId.DND_3_5E },
    [SourceBook.RacesOfTheDragon]: { id: 93, name: 'Races of the Dragon', abbreviation: 'RDr', editionId: EditionId.DND_3_5E },
    [SourceBook.RedHandOfDoom]: { id: 94, name: 'Red Hand of Doom', abbreviation: 'RH', editionId: EditionId.DND_3_5E },
    [SourceBook.PowerOfFaerun]: { id: 95, name: 'Power of Faerûn', abbreviation: 'PF', editionId: EditionId.DND_3_5E },
    [SourceBook.TomeOfMagic]: { id: 96, name: 'Tome of Magic', abbreviation: 'TM', editionId: EditionId.DND_3_5E },
    [SourceBook.CompletePsionic]: { id: 97, name: 'Complete Psionic', abbreviation: 'CP', editionId: EditionId.DND_3_5E },
    [SourceBook.FantasticLocationsFieldsOfRuin]: { id: 98, name: 'Fantastic Locations: Fields of Ruin', abbreviation: 'FLFR', editionId: EditionId.DND_3_5E },
    [SourceBook.VoyageOfTheGoldenDragon]: { id: 99, name: 'Voyage of the Golden Dragon', abbreviation: 'VGD', editionId: EditionId.DND_3_5E },
    [SourceBook.PlayersHandbookII]: { id: 100, name: "Player's Handbook II", abbreviation: 'PH2', editionId: EditionId.DND_3_5E },
    [SourceBook.FiendishCodexI]: { id: 101, name: 'Fiendish Codex I', abbreviation: 'FC1', editionId: EditionId.DND_3_5E },
    [SourceBook.MysteriesOfTheMoonsea]: { id: 102, name: 'Mysteries of the Moonsea', abbreviation: 'Mys', editionId: EditionId.DND_3_5E },
    [SourceBook.FantasticLocationsDragondownGrotto]: { id: 103, name: 'Fantastic Locations: Dragondown Grotto', abbreviation: 'FLDG', editionId: EditionId.DND_3_5E },
    [SourceBook.MonsterManualIV]: { id: 104, name: 'Monster Manual IV', abbreviation: 'MM4', editionId: EditionId.DND_3_5E },
    [SourceBook.SecretsOfXendrik]: { id: 105, name: "Secrets of Xen'drik", abbreviation: 'SX', editionId: EditionId.DND_3_5E },
    [SourceBook.DragonsOfFaerun]: { id: 106, name: 'Dragons of Faerûn', abbreviation: 'DrF', editionId: EditionId.DND_3_5E },
    [SourceBook.TomeOfBattle]: { id: 107, name: 'Tome of Battle', abbreviation: 'ToB', editionId: EditionId.DND_3_5E },
    [SourceBook.DragonMagic]: { id: 108, name: 'Dragon Magic', abbreviation: 'DM', editionId: EditionId.DND_3_5E },
    [SourceBook.FaithsOfEberron]: { id: 109, name: 'Faiths of Eberron', abbreviation: 'FE', editionId: EditionId.DND_3_5E },
    [SourceBook.TwilightTomb]: { id: 110, name: 'Twilight Tomb', abbreviation: 'TT', editionId: EditionId.DND_3_5E },
    [SourceBook.CompleteMage]: { id: 111, name: 'Complete Mage', abbreviation: 'CM', editionId: EditionId.DND_3_5E },
    [SourceBook.ExpeditionToCastleRavenloft]: { id: 112, name: 'Expedition to Castle Ravenloft', abbreviation: 'ECR', editionId: EditionId.DND_3_5E },
    [SourceBook.Cityscape]: { id: 113, name: 'Cityscape', abbreviation: 'Ci', editionId: EditionId.DND_3_5E },
    [SourceBook.Dragonmarked]: { id: 114, name: 'Dragonmarked', abbreviation: 'Dra', editionId: EditionId.DND_3_5E },
    [SourceBook.ScourgeOfTheHowlingHorde]: { id: 115, name: 'Scourge of the Howling Horde', abbreviation: 'SotHH', editionId: EditionId.DND_3_5E },
    [SourceBook.AnimatedSeriesHandbook]: { id: 116, name: 'Animated Series Handbook', abbreviation: 'ASH', editionId: EditionId.DND_3_5E },
    [SourceBook.FantasticLocationsTheFrostfellRift]: { id: 117, name: 'Fantastic Locations: The Frostfell Rift', abbreviation: 'FLTFR', editionId: EditionId.DND_3_5E },
    [SourceBook.FiendishCodexII]: { id: 118, name: 'Fiendish Codex II', abbreviation: 'FC2', editionId: EditionId.DND_3_5E },
    [SourceBook.ShatteredGatesOfSlaughtergarde]: { id: 119, name: 'Shattered Gates of Slaughtergarde', abbreviation: 'ShG', editionId: EditionId.DND_3_5E },
    [SourceBook.CompleteScoundrel]: { id: 120, name: 'Complete Scoundrel', abbreviation: 'CS', editionId: EditionId.DND_3_5E },
    [SourceBook.BarrowOfTheForgottenKing]: { id: 121, name: 'Barrow of the Forgotten King', abbreviation: 'BFK', editionId: EditionId.DND_3_5E },
    [SourceBook.Dungeonscape]: { id: 122, name: 'Dungeonscape', abbreviation: 'Du', editionId: EditionId.DND_3_5E },
    [SourceBook.SecretsOfSarlona]: { id: 123, name: 'Secrets of Sarlona', abbreviation: 'SoS', editionId: EditionId.DND_3_5E },
    [SourceBook.MagicItemCompendium]: { id: 124, name: 'Magic Item Compendium', abbreviation: 'MIC', editionId: EditionId.DND_3_5E },
    [SourceBook.CormyrTheTearingOfTheWeave]: { id: 125, name: 'Cormyr: The Tearing of the Weave', abbreviation: 'Co', editionId: EditionId.DND_3_5E },
    [SourceBook.EyesOfTheLichQueen]: { id: 126, name: 'Eyes of the Lich Queen', abbreviation: 'ELQ', editionId: EditionId.DND_3_5E },
    [SourceBook.ExpeditionToTheDemonwebPits]: { id: 127, name: 'Expedition to the Demonweb Pits', abbreviation: 'EDP', editionId: EditionId.DND_3_5E },
    [SourceBook.FantasticLocationsCityInPeril]: { id: 128, name: 'Fantastic Locations: City in Peril', abbreviation: 'FLCiP', editionId: EditionId.DND_3_5E },
    [SourceBook.CompleteChampion]: { id: 129, name: 'Complete Champion', abbreviation: 'CC', editionId: EditionId.DND_3_5E },
    [SourceBook.DrowOfTheUnderdark]: { id: 130, name: 'Drow of the Underdark', abbreviation: 'DrU', editionId: EditionId.DND_3_5E },
    [SourceBook.ExpeditionToUndermountain]: { id: 131, name: 'Expedition to Undermountain', abbreviation: 'EU', editionId: EditionId.DND_3_5E },
    [SourceBook.ForgeOfWar]: { id: 132, name: 'Forge of War', abbreviation: 'FW', editionId: EditionId.DND_3_5E },
    [SourceBook.SinisterSpire]: { id: 133, name: 'Sinister Spire', abbreviation: 'SiS', editionId: EditionId.DND_3_5E },
    [SourceBook.MonsterManualV]: { id: 134, name: 'Monster Manual V', abbreviation: 'MM5', editionId: EditionId.DND_3_5E },
    [SourceBook.ShadowdaleTheScouringOfTheLand]: { id: 135, name: 'Shadowdale: The Scouring of the Land', abbreviation: 'SSL', editionId: EditionId.DND_3_5E },
    [SourceBook.ExpeditionToTheRuinsOfGreyhawk]: { id: 136, name: 'Expedition to the Ruins of Greyhawk', abbreviation: 'ERG', editionId: EditionId.DND_3_5E },
    [SourceBook.ExemplarsOfEvil]: { id: 137, name: 'Exemplars of Evil', abbreviation: 'EE', editionId: EditionId.DND_3_5E },
    [SourceBook.FortressOfTheYuanTi]: { id: 138, name: 'Fortress of the Yuan-Ti', abbreviation: 'FY', editionId: EditionId.DND_3_5E },
    [SourceBook.GrandHistoryOfTheRealms]: { id: 139, name: 'Grand History of the Realms', abbreviation: 'GHR', editionId: EditionId.DND_3_5E },
    [SourceBook.DragonsOfEberron]: { id: 140, name: 'Dragons of Eberron', abbreviation: 'DE', editionId: EditionId.DND_3_5E },
    [SourceBook.RulesCompendium]: { id: 141, name: 'Rules Compendium', abbreviation: 'RC', editionId: EditionId.DND_3_5E },
    [SourceBook.AnaurochTheEmpireOfShade]: { id: 142, name: 'Anauroch: The Empire of Shade', abbreviation: 'An', editionId: EditionId.DND_3_5E },
    [SourceBook.ElderEvils]: { id: 143, name: 'Elder Evils', abbreviation: 'ElE', editionId: EditionId.DND_3_5E },
    [SourceBook.CityOfStormreach]: { id: 144, name: 'City of Stormreach', abbreviation: 'CoS', editionId: EditionId.DND_3_5E },
    [SourceBook.AnAdventurersGuideToEberron]: { id: 145, name: "An Adventurer's Guide to Eberron", abbreviation: 'AGE', editionId: EditionId.DND_3_5E },
};

export const SourceType = {
    Core: 0,
    Classes: 1,
    Spells: 2,
    Races: 3,
    Domains: 4,
    Deities: 5,
    Items: 6,
} as const;

export type SourceType = (typeof SourceType)[keyof typeof SourceType];

export const SOURCE_BOOK_FILTER_MAP = {
    [SourceType.Core]: [
        SourceBook.PlayersHandbook_3_0,
        SourceBook.DungeonMastersGuide_3_0,
        SourceBook.PlayersHandbook_3_5,
        SourceBook.DungeonMastersGuide_3_5,
    ],
    [SourceType.Classes]: [
        SourceBook.PlayersHandbook_3_0,
        SourceBook.DungeonMastersGuide_3_0,
        SourceBook.PlayersHandbook_3_5,
        SourceBook.DungeonMastersGuide_3_5,
        SourceBook.UnearthedArcana,
        SourceBook.CompleteWarrior,
        SourceBook.CompleteArcane,
        SourceBook.CompleteDivine,
        SourceBook.CompleteAdventurer,
        SourceBook.CompleteMage,
        SourceBook.CompleteScoundrel,
        SourceBook.CompleteChampion,
        SourceBook.RacesOfStone,
        SourceBook.RacesOfDestiny,
        SourceBook.RacesOfTheWild,
        SourceBook.RacesOfTheDragon,
        SourceBook.Frostburn,
        SourceBook.Sandstorm,
        SourceBook.Stormwrack,
        SourceBook.Dungeonscape,
        SourceBook.Cityscape,
        SourceBook.HeroesOfBattle,
        SourceBook.HeroesOfHorror,
        SourceBook.DragonMagic,
        SourceBook.PlanarHandbook,
        SourceBook.Draconomicon,
        SourceBook.DrowOfTheUnderdark,
        SourceBook.FiendFolio,
        SourceBook.LibrisMortis,
        SourceBook.LordsOfMadness,
        SourceBook.FiendishCodexI,
        SourceBook.FiendishCodexII,
        SourceBook.BookOfVileDarkness,
        SourceBook.BookOfExaltedDeeds,
        SourceBook.SavageSpecies,
        SourceBook.TomeOfBattle,
        SourceBook.TomeOfMagic,
        SourceBook.ExpandedPsionicsHandbook,
        SourceBook.CompletePsionic,
        SourceBook.PsionicsHandbook,
        SourceBook.EpicLevelHandbook,
        SourceBook.ManualOfThePlanes,
        SourceBook.DeitiesAndDemigods,
        SourceBook.DefendersOfTheFaith,
        SourceBook.SwordAndFist,
        SourceBook.TomeAndBlood,
        SourceBook.SongAndSilence,
        SourceBook.MastersOfTheWild,
        SourceBook.ForgottenRealmsCampaignSetting,
        SourceBook.EberronCampaignSetting,
        SourceBook.DragonlanceCampaignSetting,
    ],
    [SourceType.Spells]: [
        SourceBook.PlayersHandbook_3_0,
        SourceBook.PlayersHandbook_3_5,
        SourceBook.SpellCompendium,
        SourceBook.CompleteArcane,
        SourceBook.CompleteMage,
        SourceBook.CompleteDivine,
        SourceBook.CompleteChampion,
        SourceBook.RacesOfStone,
        SourceBook.RacesOfDestiny,
        SourceBook.RacesOfTheWild,
        SourceBook.RacesOfTheDragon,
        SourceBook.Frostburn,
        SourceBook.Sandstorm,
        SourceBook.Stormwrack,
        SourceBook.HeroesOfHorror,
        SourceBook.DragonMagic,
        SourceBook.PlanarHandbook,
        SourceBook.Draconomicon,
        SourceBook.DrowOfTheUnderdark,
        SourceBook.LibrisMortis,
        SourceBook.LordsOfMadness,
        SourceBook.FiendishCodexI,
        SourceBook.FiendishCodexII,
        SourceBook.BookOfVileDarkness,
        SourceBook.BookOfExaltedDeeds,
        SourceBook.SavageSpecies,
        SourceBook.TomeOfMagic,
        SourceBook.ExpandedPsionicsHandbook,
        SourceBook.CompletePsionic,
        SourceBook.PsionicsHandbook,
        SourceBook.EpicLevelHandbook,
        SourceBook.ManualOfThePlanes,
        SourceBook.MagicOfFaerun,
        SourceBook.LostEmpiresOfFaerun,
        SourceBook.ChampionsOfValor,
        SourceBook.ChampionsOfRuin,
        SourceBook.MagicOfEberron,
    ],
    [SourceType.Races]: [
        SourceBook.PlayersHandbook_3_0,
        SourceBook.PlayersHandbook_3_5,
        SourceBook.MonsterManual_3_0,
        SourceBook.MonsterManual_3_5,
        SourceBook.RacesOfStone,
        SourceBook.RacesOfDestiny,
        SourceBook.RacesOfTheWild,
        SourceBook.RacesOfTheDragon,
        SourceBook.SavageSpecies,
        SourceBook.LibrisMortis,
        SourceBook.LordsOfMadness,
        SourceBook.FiendFolio,
        SourceBook.Draconomicon,
        SourceBook.DragonMagic,
        SourceBook.DrowOfTheUnderdark,
        SourceBook.PlanarHandbook,
        SourceBook.BookOfVileDarkness,
        SourceBook.BookOfExaltedDeeds,
        SourceBook.MonsterManualII,
        SourceBook.MonsterManualIII,
        SourceBook.MonsterManualIV,
        SourceBook.MonsterManualV,
        SourceBook.RacesOfFaerun,
        SourceBook.ForgottenRealmsCampaignSetting,
        SourceBook.EberronCampaignSetting,
        SourceBook.RacesOfEberron,
        SourceBook.SecretsOfXendrik,
        SourceBook.FaithsOfEberron,
        SourceBook.DragonlanceCampaignSetting,
    ],
    [SourceType.Domains]: [
        SourceBook.PlayersHandbook_3_0,
        SourceBook.PlayersHandbook_3_5,
        SourceBook.DungeonMastersGuide_3_0,
        SourceBook.DungeonMastersGuide_3_5,
        SourceBook.CompleteDivine,
        SourceBook.CompleteChampion,
        SourceBook.DeitiesAndDemigods,
        SourceBook.FaithsAndPantheons,
        SourceBook.PlayerGuideToFaerun,
        SourceBook.ForgottenRealmsCampaignSetting,
        SourceBook.ChampionsOfValor,
        SourceBook.ChampionsOfRuin,
        SourceBook.LostEmpiresOfFaerun,
        SourceBook.FaithsOfEberron,
        SourceBook.EberronCampaignSetting,
        SourceBook.DragonlanceCampaignSetting,
        SourceBook.BookOfVileDarkness,
        SourceBook.BookOfExaltedDeeds,
        SourceBook.Sandstorm,
        SourceBook.Frostburn,
        SourceBook.Stormwrack,
        SourceBook.DragonMagic,
        SourceBook.Draconomicon,
        SourceBook.FiendishCodexI,
        SourceBook.FiendishCodexII,
        SourceBook.LibrisMortis,
    ],
    [SourceType.Deities]: [
        SourceBook.PlayersHandbook_3_0,
        SourceBook.PlayersHandbook_3_5,
        SourceBook.DeitiesAndDemigods,
        SourceBook.ForgottenRealmsCampaignSetting,
        SourceBook.FaithsAndPantheons,
        SourceBook.PlayerGuideToFaerun,
        SourceBook.ChampionsOfValor,
        SourceBook.ChampionsOfRuin,
        SourceBook.LostEmpiresOfFaerun,
        SourceBook.RacesOfFaerun,
        SourceBook.EberronCampaignSetting,
        SourceBook.FaithsOfEberron,
        SourceBook.DragonlanceCampaignSetting,
        SourceBook.BookOfVileDarkness,
        SourceBook.BookOfExaltedDeeds,
    ],
    [SourceType.Items]: [
        SourceBook.PlayersHandbook_3_0,
        SourceBook.PlayersHandbook_3_5,
        SourceBook.DungeonMastersGuide_3_0,
        SourceBook.DungeonMastersGuide_3_5,
        SourceBook.ArmsAndEquipmentGuide,
        SourceBook.MagicItemCompendium,
        SourceBook.CompleteWarrior,
        SourceBook.CompleteAdventurer,
        SourceBook.CompleteArcane,
        SourceBook.CompleteMage,
        SourceBook.CompleteScoundrel,
        SourceBook.CompleteChampion,
        SourceBook.RacesOfStone,
        SourceBook.RacesOfDestiny,
        SourceBook.RacesOfTheWild,
        SourceBook.RacesOfTheDragon,
        SourceBook.Frostburn,
        SourceBook.Sandstorm,
        SourceBook.Stormwrack,
        SourceBook.Dungeonscape,
        SourceBook.Cityscape,
        SourceBook.HeroesOfBattle,
        SourceBook.HeroesOfHorror,
        SourceBook.Draconomicon,
        SourceBook.DragonMagic,
        SourceBook.DrowOfTheUnderdark,
        SourceBook.LibrisMortis,
        SourceBook.LordsOfMadness,
        SourceBook.FiendishCodexI,
        SourceBook.FiendishCodexII,
        SourceBook.BookOfVileDarkness,
        SourceBook.BookOfExaltedDeeds,
        SourceBook.SavageSpecies,
        SourceBook.ExpandedPsionicsHandbook,
        SourceBook.CompletePsionic,
        SourceBook.EpicLevelHandbook,
        SourceBook.MagicOfFaerun,
        SourceBook.Underdark,
        SourceBook.SerpentKingdoms,
        SourceBook.UnapproachableEast,
        SourceBook.ShiningSouth,
        SourceBook.MagicOfEberron,
        SourceBook.Dragonmarked,
        SourceBook.SecretsOfXendrik,
        SourceBook.DragonlanceCampaignSetting,
    ],
} as const;

export const SOURCE_BOOK_SETTING_MAP = {
    [Setting.Greyhawk]: [],
    [Setting.Planescape]: [],
    [Setting.Ravenloft]: [],
    [Setting.Spelljammer]: [],
    [Setting.DarkSun]: [],
    [Setting.Dragonlance]: [],
    [Setting.ForgottenRealms]: [
        SourceBook.ForgottenRealmsCampaignSetting,
        SourceBook.PlayerGuideToFaerun,
        SourceBook.FaithsAndPantheons,
        SourceBook.LordsOfDarkness,
        SourceBook.MagicOfFaerun,
        SourceBook.MonstersOfFaerun,
        SourceBook.RacesOfFaerun,
        SourceBook.UnapproachableEast,
        SourceBook.ShiningSouth,
        SourceBook.SilverMarches,
        SourceBook.SerpentKingdoms,
        SourceBook.Underdark,
        SourceBook.LostEmpiresOfFaerun,
        SourceBook.ChampionsOfValor,
        SourceBook.ChampionsOfRuin,
    ],
    [Setting.Eberron]: [
        SourceBook.EberronCampaignSetting,
        SourceBook.RacesOfEberron,
        SourceBook.MagicOfEberron,
        SourceBook.FaithsOfEberron,
        SourceBook.FiveNations,
        SourceBook.SecretsOfXendrik,
        SourceBook.DragonsOfEberron,
        SourceBook.ForgeOfWar,
        SourceBook.ExplorersHandbook,
    ],
} as const;

export const SOURCE_BOOK_LIST = Object.values(SOURCE_BOOK_MAP);


const SOURCE_BOOKS_WITH_CHARACTER_OPTIONS = [...new Set([
    SourceType.Classes,
    SourceType.Spells,
    SourceType.Races,
    SourceType.Domains,
    SourceType.Deities
].flatMap(sourceType => SOURCE_BOOK_FILTER_MAP[sourceType]))];


interface SourceReference {
    sourceBookId: number;
    pageNumber?: number;
}

