import { SourceMap } from './types';

export const SOURCE_BOOK_MAP: SourceMap = {
    1: { id: 1, name: "Player's Handbook", abbr: 'PHB', edition_id: 4, has_spells: 0 },
    2: { id: 2, name: 'Sunless Citadel', abbr: 'SC', edition_id: 4, has_spells: 0 },
    3: { id: 3, name: "Dungeon Master's Guide", abbr: 'DMG', edition_id: 4, has_spells: 0 },
    4: { id: 4, name: 'Dungeons and Dragons Gazeteer', abbr: 'DDG', edition_id: 4, has_spells: 0 },
    5: { id: 5, name: 'Monster Manual', abbr: 'MM', edition_id: 4, has_spells: 0 },
    6: { id: 6, name: 'Forge of Fury', abbr: 'FoF', edition_id: 4, has_spells: 0 },
    7: { id: 7, name: "Hero Builder's Guidebook", abbr: 'HBG', edition_id: 4, has_spells: 0 },
    8: { id: 8, name: 'Speaker in Dreams', abbr: 'SiD', edition_id: 4, has_spells: 0 },
    9: { id: 9, name: 'Sword and Fist', abbr: 'SaF', edition_id: 4, has_spells: 0 },
    10: { id: 10, name: 'Monsters of Faerûn', abbr: 'MoF', edition_id: 4, has_spells: 0 },
    11: { id: 11, name: 'Psionics Handbook', abbr: 'PsH', edition_id: 4, has_spells: 0 },
    12: { id: 12, name: 'Standing Stone', abbr: 'StS', edition_id: 4, has_spells: 0 },
    13: { id: 13, name: 'Defenders of the Faith', abbr: 'DotF', edition_id: 4, has_spells: 0 },
    14: { id: 14, name: 'Forgotten Realms Campaign Setting', abbr: 'FRCS', edition_id: 4, has_spells: 1 },
    15: { id: 15, name: 'Return to the Temple of Elemental Evil', abbr: 'RToEE', edition_id: 4, has_spells: 0 },
    16: { id: 16, name: 'Heart of Nightfang Spire', abbr: 'HoNS', edition_id: 4, has_spells: 0 },
    17: { id: 17, name: 'Tome and Blood', abbr: 'TaB', edition_id: 4, has_spells: 0 },
    18: { id: 18, name: 'Magic of Faerûn', abbr: 'MagF', edition_id: 4, has_spells: 1 },
    19: { id: 19, name: 'Manual of the Planes', abbr: 'MotP', edition_id: 4, has_spells: 0 },
    20: { id: 20, name: 'Enemies and Allies', abbr: 'EA', edition_id: 4, has_spells: 0 },
    21: { id: 21, name: 'Oriental Adventures', abbr: 'OA', edition_id: 4, has_spells: 0 },
    22: { id: 22, name: 'Deep Horizon', abbr: 'DH', edition_id: 4, has_spells: 0 },
    23: { id: 23, name: 'Lords of Darkness', abbr: 'LD', edition_id: 4, has_spells: 0 },
    24: { id: 24, name: 'Song and Silence', abbr: 'SaS', edition_id: 4, has_spells: 0 },
    25: { id: 25, name: 'Lord of the Iron Fortress', abbr: 'LotIF', edition_id: 4, has_spells: 0 },
    26: { id: 26, name: 'Masters of the Wild', abbr: 'MotW', edition_id: 4, has_spells: 0 },
    27: { id: 27, name: 'Bastion of Broken Souls', abbr: 'BoBS', edition_id: 4, has_spells: 0 },
    28: { id: 28, name: 'Deities and Demigods', abbr: 'DD', edition_id: 4, has_spells: 0 },
    29: { id: 29, name: 'Faiths and Pantheons', abbr: 'FP', edition_id: 4, has_spells: 0 },
    30: { id: 30, name: "Stronghold Builder's Guidebook", abbr: 'SBG', edition_id: 4, has_spells: 0 },
    31: { id: 31, name: 'Book of Challenges', abbr: 'BoC', edition_id: 4, has_spells: 0 },
    32: { id: 32, name: 'Epic Level Handbook', abbr: 'EL', edition_id: 4, has_spells: 0 },
    33: { id: 33, name: 'Silver Marches', abbr: 'SM', edition_id: 4, has_spells: 0 },
    34: { id: 34, name: 'City of the Spider Queen', abbr: 'CSQ', edition_id: 4, has_spells: 0 },
    35: { id: 35, name: 'Monster Manual II', abbr: 'MM2', edition_id: 4, has_spells: 0 },
    36: { id: 36, name: 'Book of Vile Darkness', abbr: 'BoVD', edition_id: 4, has_spells: 1 },
    37: { id: 37, name: 'Savage Species', abbr: 'SS', edition_id: 4, has_spells: 0 },
    38: { id: 38, name: 'Arms and Equipment Guide', abbr: 'AEG', edition_id: 4, has_spells: 0 },
    39: { id: 39, name: 'Races of Faerûn', abbr: 'RacF', edition_id: 4, has_spells: 1 },
    40: { id: 40, name: 'Fiend Folio', abbr: 'FF', edition_id: 4, has_spells: 0 },
    41: { id: 41, name: 'Unapproachable East', abbr: 'UnaE', edition_id: 4, has_spells: 0 },
    42: { id: 42, name: 'Ghostwalk', abbr: 'GhW', edition_id: 4, has_spells: 0 },
    43: { id: 43, name: "Dungeon Master's Guide", abbr: 'DMG', edition_id: 5, has_spells: 0 },
    44: { id: 44, name: 'Monster Manual', abbr: 'MM', edition_id: 5, has_spells: 0 },
    45: { id: 45, name: "Player's Handbook", abbr: 'PHB', edition_id: 5, has_spells: 1 },
    46: { id: 46, name: 'Dragonlance Campaign Setting', abbr: 'DCS', edition_id: 5, has_spells: 0 },
    47: { id: 47, name: 'Miniatures Handbook', abbr: 'MH', edition_id: 5, has_spells: 1 },
    48: { id: 48, name: 'Book of Exalted Deeds', abbr: 'BoED', edition_id: 5, has_spells: 1 },
    49: { id: 49, name: 'Underdark', abbr: 'Und', edition_id: 5, has_spells: 0 },
    50: { id: 50, name: 'Draconomicon', abbr: 'Dr', edition_id: 5, has_spells: 1 },
    51: { id: 51, name: 'Complete Warrior', abbr: 'CW', edition_id: 5, has_spells: 1 },
    52: { id: 52, name: 'Unearthed Arcana', abbr: 'UA', edition_id: 5, has_spells: 0 },
    53: { id: 53, name: "Player's Guide to Faerûn", abbr: 'PG', edition_id: 5, has_spells: 1 },
    54: { id: 54, name: 'Expanded Psionics Handbook', abbr: 'XPH', edition_id: 5, has_spells: 0 },
    55: { id: 55, name: 'Complete Divine', abbr: 'CD', edition_id: 5, has_spells: 1 },
    56: { id: 56, name: 'Eberron Campaign Setting', abbr: 'ECS', edition_id: 5, has_spells: 1 },
    57: { id: 57, name: 'Planar Handbook', abbr: 'PlH', edition_id: 5, has_spells: 1 },
    58: { id: 58, name: 'Serpent Kingdoms', abbr: 'SK', edition_id: 5, has_spells: 0 },
    59: { id: 59, name: 'Shadows of the Last War', abbr: 'SL', edition_id: 5, has_spells: 0 },
    60: { id: 60, name: 'Races of Stone', abbr: 'RS', edition_id: 5, has_spells: 1 },
    61: { id: 61, name: 'Frostburn', abbr: 'Fr', edition_id: 5, has_spells: 1 },
    62: { id: 62, name: 'Monster Manual III', abbr: 'MM3', edition_id: 5, has_spells: 0 },
    63: { id: 63, name: 'Libris Mortis', abbr: 'LM', edition_id: 5, has_spells: 1 },
    64: { id: 64, name: 'Shining South', abbr: 'ShS', edition_id: 5, has_spells: 0 },
    65: { id: 65, name: "Whispers of the Vampire's Blade", abbr: 'WB', edition_id: 5, has_spells: 0 },
    66: { id: 66, name: 'Complete Arcane', abbr: 'CAr', edition_id: 5, has_spells: 1 },
    67: { id: 67, name: 'Sharn: City of Towers', abbr: 'Sh', edition_id: 5, has_spells: 0 },
    68: { id: 68, name: 'Races of Destiny', abbr: 'RD', edition_id: 5, has_spells: 1 },
    69: { id: 69, name: 'Complete Adventurer', abbr: 'CAd', edition_id: 5, has_spells: 1 },
    70: { id: 70, name: 'Grasp of the Emerald Claw', abbr: 'GC', edition_id: 5, has_spells: 0 },
    71: { id: 71, name: 'Lost Empires of Faerûn', abbr: 'LE', edition_id: 5, has_spells: 0 },
    72: { id: 72, name: 'Races of the Wild', abbr: 'RW', edition_id: 5, has_spells: 1 },
    73: { id: 73, name: 'Sandstorm', abbr: 'Sa', edition_id: 5, has_spells: 1 },
    74: { id: 74, name: 'Lords of Madness', abbr: 'LoM', edition_id: 5, has_spells: 0 },
    75: { id: 75, name: 'Races of Eberron', abbr: 'RE', edition_id: 5, has_spells: 0 },
    76: { id: 76, name: 'Champions of Ruin', abbr: 'CR', edition_id: 5, has_spells: 0 },
    77: { id: 77, name: 'Heroes of Battle', abbr: 'HB', edition_id: 5, has_spells: 1 },
    78: { id: 78, name: 'City of Splendors: Waterdeep', abbr: 'CSW', edition_id: 5, has_spells: 0 },
    79: { id: 79, name: "Dungeon Master's Guide II", abbr: 'DMG2', edition_id: 5, has_spells: 0 },
    80: { id: 80, name: 'Five Nations', abbr: 'FN', edition_id: 5, has_spells: 0 },
    81: { id: 81, name: 'Weapons of Legacy', abbr: 'WL', edition_id: 5, has_spells: 0 },
    82: { id: 82, name: "Explorer's Handbook", abbr: 'EH', edition_id: 5, has_spells: 0 },
    83: { id: 83, name: 'Stormwrack', abbr: 'Sto', edition_id: 5, has_spells: 1 },
    84: { id: 84, name: 'Fantastic Locations: Fane of the Drow', abbr: 'FLFD', edition_id: 5, has_spells: 0 },
    85: { id: 85, name: 'Magic of Incarnum', abbr: 'MoI', edition_id: 5, has_spells: 1 },
    86: { id: 86, name: 'Sons of Gruumsh', abbr: 'SG', edition_id: 5, has_spells: 0 },
    87: { id: 87, name: 'Heroes of Horror', abbr: 'HH', edition_id: 5, has_spells: 1 },
    88: { id: 88, name: 'Magic of Eberron', abbr: 'MoE', edition_id: 5, has_spells: 0 },
    89: { id: 89, name: 'Champions of Valor', abbr: 'CV', edition_id: 5, has_spells: 0 },
    90: { id: 90, name: 'Fantastic Locations: Hellspike Prison', abbr: 'FLHP', edition_id: 5, has_spells: 0 },
    91: { id: 91, name: 'Spell Compendium', abbr: 'SpC', edition_id: 5, has_spells: 1 },
    92: { id: 92, name: "Player's Guide to Eberron", abbr: 'PE', edition_id: 5, has_spells: 0 },
    93: { id: 93, name: 'Races of the Dragon', abbr: 'RDr', edition_id: 5, has_spells: 1 },
    94: { id: 94, name: 'Red Hand of Doom', abbr: 'RH', edition_id: 5, has_spells: 0 },
    95: { id: 95, name: 'Power of Faerûn', abbr: 'PF', edition_id: 5, has_spells: 0 },
    96: { id: 96, name: 'Tome of Magic', abbr: 'TM', edition_id: 5, has_spells: 0 },
    97: { id: 97, name: 'Complete Psionic', abbr: 'CP', edition_id: 5, has_spells: 0 },
    98: { id: 98, name: 'Fantastic Locations: Fields of Ruin', abbr: 'FLFR', edition_id: 5, has_spells: 0 },
    99: { id: 99, name: 'Voyage of the Golden Dragon', abbr: 'VGD', edition_id: 5, has_spells: 0 },
    100: { id: 100, name: "Player's Handbook II", abbr: 'PH2', edition_id: 5, has_spells: 1 },
    101: { id: 101, name: 'Fiendish Codex I', abbr: 'FC1', edition_id: 5, has_spells: 0 },
    102: { id: 102, name: 'Mysteries of the Moonsea', abbr: 'Mys', edition_id: 5, has_spells: 0 },
    103: { id: 103, name: 'Fantastic Locations: Dragondown Grotto', abbr: 'FLDG', edition_id: 5, has_spells: 0 },
    104: { id: 104, name: 'Monster Manual IV', abbr: 'MM4', edition_id: 5, has_spells: 0 },
    105: { id: 105, name: "Secrets of Xen'drik", abbr: 'SX', edition_id: 5, has_spells: 0 },
    106: { id: 106, name: 'Dragons of Faerûn', abbr: 'DrF', edition_id: 5, has_spells: 0 },
    107: { id: 107, name: 'Tome of Battle', abbr: 'ToB', edition_id: 5, has_spells: 0 },
    108: { id: 108, name: 'Dragon Magic', abbr: 'DM', edition_id: 5, has_spells: 1 },
    109: { id: 109, name: 'Faiths of Eberron', abbr: 'FE', edition_id: 5, has_spells: 0 },
    110: { id: 110, name: 'Twilight Tomb', abbr: 'TT', edition_id: 5, has_spells: 0 },
    111: { id: 111, name: 'Complete Mage', abbr: 'CM', edition_id: 5, has_spells: 1 },
    112: { id: 112, name: 'Expedition to Castle Ravenloft', abbr: 'ECR', edition_id: 5, has_spells: 0 },
    113: { id: 113, name: 'Cityscape', abbr: 'Ci', edition_id: 5, has_spells: 1 },
    114: { id: 114, name: 'Dragonmarked', abbr: 'Dra', edition_id: 5, has_spells: 0 },
    115: { id: 115, name: 'Scourge of the Howling Horde', abbr: 'SotHH', edition_id: 5, has_spells: 0 },
    116: { id: 116, name: 'Animated Series Handbook', abbr: 'ASH', edition_id: 5, has_spells: 0 },
    117: { id: 117, name: 'Fantastic Locations: The Frostfell Rift', abbr: 'FLTFR', edition_id: 5, has_spells: 0 },
    118: { id: 118, name: 'Fiendish Codex II', abbr: 'FC2', edition_id: 5, has_spells: 0 },
    119: { id: 119, name: 'Shattered Gates of Slaughtergarde', abbr: 'ShG', edition_id: 5, has_spells: 0 },
    120: { id: 120, name: 'Complete Scoundrel', abbr: 'CS', edition_id: 5, has_spells: 0 },
    121: { id: 121, name: 'Barrow of the Forgotten King', abbr: 'BFK', edition_id: 5, has_spells: 0 },
    122: { id: 122, name: 'Dungeonscape', abbr: 'Du', edition_id: 5, has_spells: 0 },
    123: { id: 123, name: 'Secrets of Sarlona', abbr: 'SoS', edition_id: 5, has_spells: 0 },
    124: { id: 124, name: 'Magic Item Compendium', abbr: 'MIC', edition_id: 5, has_spells: 0 },
    125: { id: 125, name: 'Cormyr: The Tearing of the Weave', abbr: 'Co', edition_id: 5, has_spells: 0 },
    126: { id: 126, name: 'Eyes of the Lich Queen', abbr: 'ELQ', edition_id: 5, has_spells: 0 },
    127: { id: 127, name: 'Expedition to the Demonweb Pits', abbr: 'EDP', edition_id: 5, has_spells: 0 },
    128: { id: 128, name: 'Fantastic Locations: City in Peril', abbr: 'FLCiP', edition_id: 5, has_spells: 0 },
    129: { id: 129, name: 'Complete Champion', abbr: 'CC', edition_id: 5, has_spells: 1 },
    130: { id: 130, name: 'Drow of the Underdark', abbr: 'DrU', edition_id: 5, has_spells: 1 },
    131: { id: 131, name: 'Expedition to Undermountain', abbr: 'EU', edition_id: 5, has_spells: 0 },
    132: { id: 132, name: 'Forge of War', abbr: 'FW', edition_id: 5, has_spells: 0 },
    133: { id: 133, name: 'Sinister Spire', abbr: 'SiS', edition_id: 5, has_spells: 0 },
    134: { id: 134, name: 'Monster Manual V', abbr: 'MM5', edition_id: 5, has_spells: 0 },
    135: { id: 135, name: 'Shadowdale: The Scouring of the Land', abbr: 'SSL', edition_id: 5, has_spells: 0 },
    136: { id: 136, name: 'Expedition to the Ruins of Greyhawk', abbr: 'ERG', edition_id: 5, has_spells: 0 },
    137: { id: 137, name: 'Exemplars of Evil', abbr: 'EE', edition_id: 5, has_spells: 0 },
    138: { id: 138, name: 'Fortress of the Yuan-Ti', abbr: 'FY', edition_id: 5, has_spells: 0 },
    139: { id: 139, name: 'Grand History of the Realms', abbr: 'GHR', edition_id: 5, has_spells: 0 },
    140: { id: 140, name: 'Dragons of Eberron', abbr: 'DE', edition_id: 5, has_spells: 0 },
    141: { id: 141, name: 'Rules Compendium', abbr: 'RC', edition_id: 5, has_spells: 0 },
    142: { id: 142, name: 'Anauroch: The Empire of Shade', abbr: 'An', edition_id: 5, has_spells: 0 },
    143: { id: 143, name: 'Elder Evils', abbr: 'ElE', edition_id: 5, has_spells: 0 },
    144: { id: 144, name: 'City of Stormreach', abbr: 'CoS', edition_id: 5, has_spells: 0 },
    145: { id: 145, name: "An Adventurer's Guide to Eberron", abbr: 'AGE', edition_id: 5, has_spells: 0 },
}

export const SOURCE_BOOK_LIST = Object.values(SOURCE_BOOK_MAP);

interface SourceReference {
    book_id: number;
    page_number?: number;
}

export function GetSourceDisplay(sources: SourceReference[], useAbbrev: boolean = false): string {
    if (!sources || sources.length === 0) return '';

    return sources.map(source => {
        const book = SOURCE_BOOK_MAP[source.book_id];
        if (book) {
            const displayTitle = useAbbrev ? book.abbr : book.name;
            return source.page_number ? `${displayTitle} (pg ${source.page_number})` : displayTitle;
        }
        return 'Unknown Source';
    }).join(', ');
} 