import type { SourceBookMap } from './types';
import { NameSelectOptionList } from './Util';

export const SOURCE_BOOK_MAP: SourceBookMap = {
    1: { id: 1, name: "Player's Handbook", abbreviation: 'PHB', editionId: 4, hasSpells: false, hasClasses: true },
    2: { id: 2, name: 'Sunless Citadel', abbreviation: 'SC', editionId: 4, hasSpells: false, hasClasses: false },
    3: { id: 3, name: "Dungeon Master's Guide", abbreviation: 'DMG', editionId: 4, hasSpells: false, hasClasses: true },
    4: { id: 4, name: 'Dungeons and Dragons Gazeteer', abbreviation: 'DDG', editionId: 4, hasSpells: false, hasClasses: false },
    5: { id: 5, name: 'Monster Manual', abbreviation: 'MM', editionId: 4, hasSpells: false, hasClasses: false },
    6: { id: 6, name: 'Forge of Fury', abbreviation: 'FoF', editionId: 4, hasSpells: false, hasClasses: false },
    7: { id: 7, name: "Hero Builder's Guidebook", abbreviation: 'HBG', editionId: 4, hasSpells: false, hasClasses: false },
    8: { id: 8, name: 'Speaker in Dreams', abbreviation: 'SiD', editionId: 4, hasSpells: false, hasClasses: false },
    9: { id: 9, name: 'Sword and Fist', abbreviation: 'SaF', editionId: 4, hasSpells: false, hasClasses: false },
    10: { id: 10, name: 'Monsters of Faerûn', abbreviation: 'MoF', editionId: 4, hasSpells: false, hasClasses: false },
    11: { id: 11, name: 'Psionics Handbook', abbreviation: 'PsH', editionId: 4, hasSpells: false, hasClasses: false },
    12: { id: 12, name: 'Standing Stone', abbreviation: 'StS', editionId: 4, hasSpells: false, hasClasses: false },
    13: { id: 13, name: 'Defenders of the Faith', abbreviation: 'DotF', editionId: 4, hasSpells: false, hasClasses: true },
    14: { id: 14, name: 'Forgotten Realms Campaign Setting', abbreviation: 'FRCS', editionId: 4, hasSpells: true, hasClasses: false },
    15: { id: 15, name: 'Return to the Temple of Elemental Evil', abbreviation: 'RToEE', editionId: 4, hasSpells: false, hasClasses: false },
    16: { id: 16, name: 'Heart of Nightfang Spire', abbreviation: 'HoNS', editionId: 4, hasSpells: false, hasClasses: false },
    17: { id: 17, name: 'Tome and Blood', abbreviation: 'TaB', editionId: 4, hasSpells: false, hasClasses: false },
    18: { id: 18, name: 'Magic of Faerûn', abbreviation: 'MagF', editionId: 4, hasSpells: true, hasClasses: true },
    19: { id: 19, name: 'Manual of the Planes', abbreviation: 'MotP', editionId: 4, hasSpells: false, hasClasses: false },
    20: { id: 20, name: 'Enemies and Allies', abbreviation: 'EA', editionId: 4, hasSpells: false, hasClasses: false },
    21: { id: 21, name: 'Oriental Adventures', abbreviation: 'OA', editionId: 4, hasSpells: false, hasClasses: false },
    22: { id: 22, name: 'Deep Horizon', abbreviation: 'DH', editionId: 4, hasSpells: false, hasClasses: false },
    23: { id: 23, name: 'Lords of Darkness', abbreviation: 'LD', editionId: 4, hasSpells: false, hasClasses: false },
    24: { id: 24, name: 'Song and Silence', abbreviation: 'SaS', editionId: 4, hasSpells: false, hasClasses: false },
    25: { id: 25, name: 'Lord of the Iron Fortress', abbreviation: 'LotIF', editionId: 4, hasSpells: false, hasClasses: false },
    26: { id: 26, name: 'Masters of the Wild', abbreviation: 'MotW', editionId: 4, hasSpells: false, hasClasses: false },
    27: { id: 27, name: 'Bastion of Broken Souls', abbreviation: 'BoBS', editionId: 4, hasSpells: false, hasClasses: false },
    28: { id: 28, name: 'Deities and Demigods', abbreviation: 'DD', editionId: 4, hasSpells: false, hasClasses: false },
    29: { id: 29, name: 'Faiths and Pantheons', abbreviation: 'FP', editionId: 4, hasSpells: false, hasClasses: true },
    30: { id: 30, name: "Stronghold Builder's Guidebook", abbreviation: 'SBG', editionId: 4, hasSpells: false, hasClasses: false },
    31: { id: 31, name: 'Book of Challenges', abbreviation: 'BoC', editionId: 4, hasSpells: false, hasClasses: false },
    32: { id: 32, name: 'Epic Level Handbook', abbreviation: 'EL', editionId: 4, hasSpells: false, hasClasses: false },
    33: { id: 33, name: 'Silver Marches', abbreviation: 'SM', editionId: 4, hasSpells: false, hasClasses: false },
    34: { id: 34, name: 'City of the Spider Queen', abbreviation: 'CSQ', editionId: 4, hasSpells: false, hasClasses: false },
    35: { id: 35, name: 'Monster Manual II', abbreviation: 'MM2', editionId: 4, hasSpells: false, hasClasses: false },
    36: { id: 36, name: 'Book of Vile Darkness', abbreviation: 'BoVD', editionId: 4, hasSpells: true, hasClasses: true },
    37: { id: 37, name: 'Savage Species', abbreviation: 'SS', editionId: 4, hasSpells: false, hasClasses: false },
    38: { id: 38, name: 'Arms and Equipment Guide', abbreviation: 'AEG', editionId: 4, hasSpells: false, hasClasses: false },
    39: { id: 39, name: 'Races of Faerûn', abbreviation: 'RacF', editionId: 4, hasSpells: true, hasClasses: false },
    40: { id: 40, name: 'Fiend Folio', abbreviation: 'FF', editionId: 4, hasSpells: false, hasClasses: false },
    41: { id: 41, name: 'Unapproachable East', abbreviation: 'UnaE', editionId: 4, hasSpells: false, hasClasses: false },
    42: { id: 42, name: 'Ghostwalk', abbreviation: 'GhW', editionId: 4, hasSpells: false, hasClasses: false },
    43: { id: 43, name: "Dungeon Master's Guide", abbreviation: 'DMG', editionId: 5, hasSpells: false, hasClasses: true },
    44: { id: 44, name: 'Monster Manual', abbreviation: 'MM', editionId: 5, hasSpells: false, hasClasses: false },
    45: { id: 45, name: "Player's Handbook", abbreviation: 'PHB', editionId: 5, hasSpells: true, hasClasses: true },
    46: { id: 46, name: 'Dragonlance Campaign Setting', abbreviation: 'DCS', editionId: 5, hasSpells: false, hasClasses: false },
    47: { id: 47, name: 'Miniatures Handbook', abbreviation: 'MH', editionId: 5, hasSpells: true, hasClasses: true },
    48: { id: 48, name: 'Book of Exalted Deeds', abbreviation: 'BoED', editionId: 5, hasSpells: true, hasClasses: true },
    49: { id: 49, name: 'Underdark', abbreviation: 'Und', editionId: 5, hasSpells: false, hasClasses: false },
    50: { id: 50, name: 'Draconomicon', abbreviation: 'Dr', editionId: 5, hasSpells: true, hasClasses: true },
    51: { id: 51, name: 'Complete Warrior', abbreviation: 'CW', editionId: 5, hasSpells: true, hasClasses: true },
    52: { id: 52, name: 'Unearthed Arcana', abbreviation: 'UA', editionId: 5, hasSpells: false, hasClasses: false },
    53: { id: 53, name: "Player's Guide to Faerûn", abbreviation: 'PG', editionId: 5, hasSpells: true, hasClasses: false },
    54: { id: 54, name: 'Expanded Psionics Handbook', abbreviation: 'XPH', editionId: 5, hasSpells: false, hasClasses: true },
    55: { id: 55, name: 'Complete Divine', abbreviation: 'CD', editionId: 5, hasSpells: true, hasClasses: true },
    56: { id: 56, name: 'Eberron Campaign Setting', abbreviation: 'ECS', editionId: 5, hasSpells: true, hasClasses: true },
    57: { id: 57, name: 'Planar Handbook', abbreviation: 'PlH', editionId: 5, hasSpells: true, hasClasses: true },
    58: { id: 58, name: 'Serpent Kingdoms', abbreviation: 'SK', editionId: 5, hasSpells: false, hasClasses: false },
    59: { id: 59, name: 'Shadows of the Last War', abbreviation: 'SL', editionId: 5, hasSpells: false, hasClasses: false },
    60: { id: 60, name: 'Races of Stone', abbreviation: 'RS', editionId: 5, hasSpells: true, hasClasses: false },
    61: { id: 61, name: 'Frostburn', abbreviation: 'Fr', editionId: 5, hasSpells: true, hasClasses: true },
    62: { id: 62, name: 'Monster Manual III', abbreviation: 'MM3', editionId: 5, hasSpells: false, hasClasses: false },
    63: { id: 63, name: 'Libris Mortis', abbreviation: 'LM', editionId: 5, hasSpells: true, hasClasses: false },
    64: { id: 64, name: 'Shining South', abbreviation: 'ShS', editionId: 5, hasSpells: false, hasClasses: false },
    65: { id: 65, name: "Whispers of the Vampire's Blade", abbreviation: 'WB', editionId: 5, hasSpells: false, hasClasses: false },
    66: { id: 66, name: 'Complete Arcane', abbreviation: 'CAr', editionId: 5, hasSpells: true, hasClasses: true },
    67: { id: 67, name: 'Sharn: City of Towers', abbreviation: 'Sh', editionId: 5, hasSpells: false, hasClasses: false },
    68: { id: 68, name: 'Races of Destiny', abbreviation: 'RD', editionId: 5, hasSpells: true, hasClasses: false },
    69: { id: 69, name: 'Complete Adventurer', abbreviation: 'CAd', editionId: 5, hasSpells: true, hasClasses: true },
    70: { id: 70, name: 'Grasp of the Emerald Claw', abbreviation: 'GC', editionId: 5, hasSpells: false, hasClasses: false },
    71: { id: 71, name: 'Lost Empires of Faerûn', abbreviation: 'LE', editionId: 5, hasSpells: false, hasClasses: false },
    72: { id: 72, name: 'Races of the Wild', abbreviation: 'RW', editionId: 5, hasSpells: true, hasClasses: false },
    73: { id: 73, name: 'Sandstorm', abbreviation: 'Sa', editionId: 5, hasSpells: true, hasClasses: false },
    74: { id: 74, name: 'Lords of Madness', abbreviation: 'LoM', editionId: 5, hasSpells: false, hasClasses: false },
    75: { id: 75, name: 'Races of Eberron', abbreviation: 'RE', editionId: 5, hasSpells: false, hasClasses: false },
    76: { id: 76, name: 'Champions of Ruin', abbreviation: 'CR', editionId: 5, hasSpells: false, hasClasses: false },
    77: { id: 77, name: 'Heroes of Battle', abbreviation: 'HB', editionId: 5, hasSpells: true, hasClasses: false },
    78: { id: 78, name: 'City of Splendors: Waterdeep', abbreviation: 'CSW', editionId: 5, hasSpells: false, hasClasses: false },
    79: { id: 79, name: "Dungeon Master's Guide II", abbreviation: 'DMG2', editionId: 5, hasSpells: false, hasClasses: false },
    80: { id: 80, name: 'Five Nations', abbreviation: 'FN', editionId: 5, hasSpells: false, hasClasses: false },
    81: { id: 81, name: 'Weapons of Legacy', abbreviation: 'WL', editionId: 5, hasSpells: false, hasClasses: false },
    82: { id: 82, name: "Explorer's Handbook", abbreviation: 'EH', editionId: 5, hasSpells: false, hasClasses: false },
    83: { id: 83, name: 'Stormwrack', abbreviation: 'Sto', editionId: 5, hasSpells: true, hasClasses: false },
    84: { id: 84, name: 'Fantastic Locations: Fane of the Drow', abbreviation: 'FLFD', editionId: 5, hasSpells: false, hasClasses: false },
    85: { id: 85, name: 'Magic of Incarnum', abbreviation: 'MoI', editionId: 5, hasSpells: true, hasClasses: false },
    86: { id: 86, name: 'Sons of Gruumsh', abbreviation: 'SG', editionId: 5, hasSpells: false, hasClasses: false },
    87: { id: 87, name: 'Heroes of Horror', abbreviation: 'HH', editionId: 5, hasSpells: true, hasClasses: true },
    88: { id: 88, name: 'Magic of Eberron', abbreviation: 'MoE', editionId: 5, hasSpells: false, hasClasses: false },
    89: { id: 89, name: 'Champions of Valor', abbreviation: 'CV', editionId: 5, hasSpells: false, hasClasses: false },
    90: { id: 90, name: 'Fantastic Locations: Hellspike Prison', abbreviation: 'FLHP', editionId: 5, hasSpells: false, hasClasses: false },
    91: { id: 91, name: 'Spell Compendium', abbreviation: 'SpC', editionId: 5, hasSpells: true, hasClasses: false },
    92: { id: 92, name: "Player's Guide to Eberron", abbreviation: 'PE', editionId: 5, hasSpells: false, hasClasses: false },
    93: { id: 93, name: 'Races of the Dragon', abbreviation: 'RDr', editionId: 5, hasSpells: true, hasClasses: false },
    94: { id: 94, name: 'Red Hand of Doom', abbreviation: 'RH', editionId: 5, hasSpells: false, hasClasses: false },
    95: { id: 95, name: 'Power of Faerûn', abbreviation: 'PF', editionId: 5, hasSpells: false, hasClasses: false },
    96: { id: 96, name: 'Tome of Magic', abbreviation: 'TM', editionId: 5, hasSpells: false, hasClasses: false },
    97: { id: 97, name: 'Complete Psionic', abbreviation: 'CP', editionId: 5, hasSpells: false, hasClasses: false },
    98: { id: 98, name: 'Fantastic Locations: Fields of Ruin', abbreviation: 'FLFR', editionId: 5, hasSpells: false, hasClasses: false },
    99: { id: 99, name: 'Voyage of the Golden Dragon', abbreviation: 'VGD', editionId: 5, hasSpells: false, hasClasses: false },
    100: { id: 100, name: "Player's Handbook II", abbreviation: 'PH2', editionId: 5, hasSpells: true, hasClasses: true },
    101: { id: 101, name: 'Fiendish Codex I', abbreviation: 'FC1', editionId: 5, hasSpells: false, hasClasses: false },
    102: { id: 102, name: 'Mysteries of the Moonsea', abbreviation: 'Mys', editionId: 5, hasSpells: false, hasClasses: false },
    103: { id: 103, name: 'Fantastic Locations: Dragondown Grotto', abbreviation: 'FLDG', editionId: 5, hasSpells: false, hasClasses: false },
    104: { id: 104, name: 'Monster Manual IV', abbreviation: 'MM4', editionId: 5, hasSpells: false, hasClasses: false },
    105: { id: 105, name: "Secrets of Xen'drik", abbreviation: 'SX', editionId: 5, hasSpells: false, hasClasses: false },
    106: { id: 106, name: 'Dragons of Faerûn', abbreviation: 'DrF', editionId: 5, hasSpells: false, hasClasses: false },
    107: { id: 107, name: 'Tome of Battle', abbreviation: 'ToB', editionId: 5, hasSpells: false, hasClasses: false },
    108: { id: 108, name: 'Dragon Magic', abbreviation: 'DM', editionId: 5, hasSpells: true, hasClasses: false },
    109: { id: 109, name: 'Faiths of Eberron', abbreviation: 'FE', editionId: 5, hasSpells: false, hasClasses: false },
    110: { id: 110, name: 'Twilight Tomb', abbreviation: 'TT', editionId: 5, hasSpells: false, hasClasses: false },
    111: { id: 111, name: 'Complete Mage', abbreviation: 'CM', editionId: 5, hasSpells: true, hasClasses: false },
    112: { id: 112, name: 'Expedition to Castle Ravenloft', abbreviation: 'ECR', editionId: 5, hasSpells: false, hasClasses: false },
    113: { id: 113, name: 'Cityscape', abbreviation: 'Ci', editionId: 5, hasSpells: true, hasClasses: false },
    114: { id: 114, name: 'Dragonmarked', abbreviation: 'Dra', editionId: 5, hasSpells: false, hasClasses: false },
    115: { id: 115, name: 'Scourge of the Howling Horde', abbreviation: 'SotHH', editionId: 5, hasSpells: false, hasClasses: false },
    116: { id: 116, name: 'Animated Series Handbook', abbreviation: 'ASH', editionId: 5, hasSpells: false, hasClasses: false },
    117: { id: 117, name: 'Fantastic Locations: The Frostfell Rift', abbreviation: 'FLTFR', editionId: 5, hasSpells: false, hasClasses: false },
    118: { id: 118, name: 'Fiendish Codex II', abbreviation: 'FC2', editionId: 5, hasSpells: false, hasClasses: false },
    119: { id: 119, name: 'Shattered Gates of Slaughtergarde', abbreviation: 'ShG', editionId: 5, hasSpells: false, hasClasses: false },
    120: { id: 120, name: 'Complete Scoundrel', abbreviation: 'CS', editionId: 5, hasSpells: false, hasClasses: false },
    121: { id: 121, name: 'Barrow of the Forgotten King', abbreviation: 'BFK', editionId: 5, hasSpells: false, hasClasses: false },
    122: { id: 122, name: 'Dungeonscape', abbreviation: 'Du', editionId: 5, hasSpells: false, hasClasses: false },
    123: { id: 123, name: 'Secrets of Sarlona', abbreviation: 'SoS', editionId: 5, hasSpells: false, hasClasses: false },
    124: { id: 124, name: 'Magic Item Compendium', abbreviation: 'MIC', editionId: 5, hasSpells: false, hasClasses: false },
    125: { id: 125, name: 'Cormyr: The Tearing of the Weave', abbreviation: 'Co', editionId: 5, hasSpells: false, hasClasses: false },
    126: { id: 126, name: 'Eyes of the Lich Queen', abbreviation: 'ELQ', editionId: 5, hasSpells: false, hasClasses: false },
    127: { id: 127, name: 'Expedition to the Demonweb Pits', abbreviation: 'EDP', editionId: 5, hasSpells: false, hasClasses: false },
    128: { id: 128, name: 'Fantastic Locations: City in Peril', abbreviation: 'FLCiP', editionId: 5, hasSpells: false, hasClasses: false },
    129: { id: 129, name: 'Complete Champion', abbreviation: 'CC', editionId: 5, hasSpells: true, hasClasses: false },
    130: { id: 130, name: 'Drow of the Underdark', abbreviation: 'DrU', editionId: 5, hasSpells: true, hasClasses: false },
    131: { id: 131, name: 'Expedition to Undermountain', abbreviation: 'EU', editionId: 5, hasSpells: false, hasClasses: false },
    132: { id: 132, name: 'Forge of War', abbreviation: 'FW', editionId: 5, hasSpells: false, hasClasses: false },
    133: { id: 133, name: 'Sinister Spire', abbreviation: 'SiS', editionId: 5, hasSpells: false, hasClasses: false },
    134: { id: 134, name: 'Monster Manual V', abbreviation: 'MM5', editionId: 5, hasSpells: false, hasClasses: false },
    135: { id: 135, name: 'Shadowdale: The Scouring of the Land', abbreviation: 'SSL', editionId: 5, hasSpells: false, hasClasses: false },
    136: { id: 136, name: 'Expedition to the Ruins of Greyhawk', abbreviation: 'ERG', editionId: 5, hasSpells: false, hasClasses: false },
    137: { id: 137, name: 'Exemplars of Evil', abbreviation: 'EE', editionId: 5, hasSpells: false, hasClasses: false },
    138: { id: 138, name: 'Fortress of the Yuan-Ti', abbreviation: 'FY', editionId: 5, hasSpells: false, hasClasses: false },
    139: { id: 139, name: 'Grand History of the Realms', abbreviation: 'GHR', editionId: 5, hasSpells: false, hasClasses: false },
    140: { id: 140, name: 'Dragons of Eberron', abbreviation: 'DE', editionId: 5, hasSpells: false, hasClasses: false },
    141: { id: 141, name: 'Rules Compendium', abbreviation: 'RC', editionId: 5, hasSpells: false, hasClasses: false },
    142: { id: 142, name: 'Anauroch: The Empire of Shade', abbreviation: 'An', editionId: 5, hasSpells: false, hasClasses: false },
    143: { id: 143, name: 'Elder Evils', abbreviation: 'ElE', editionId: 5, hasSpells: false, hasClasses: false },
    144: { id: 144, name: 'City of Stormreach', abbreviation: 'CoS', editionId: 5, hasSpells: false, hasClasses: false },
    145: { id: 145, name: "An Adventurer's Guide to Eberron", abbreviation: 'AGE', editionId: 5, hasSpells: false, hasClasses: false },
};

export const SOURCE_BOOK_LIST = Object.values(SOURCE_BOOK_MAP);
export const SOURCE_BOOK_WITH_CLASSES_SELECT_LIST = NameSelectOptionList(SOURCE_BOOK_LIST.filter(sourceBook => sourceBook.hasClasses));
export const SOURCE_BOOK_WITH_SPELLS_SELECT_LIST = NameSelectOptionList(SOURCE_BOOK_LIST.filter(sourceBook => sourceBook.hasSpells));

interface SourceReference {
    bookId: number;
    pageNumber?: number;
}

export function GetSourceDisplay(sources: SourceReference[], useAbbrev: boolean = false): string {
    if (!sources || sources.length === 0) return '';

    return sources.map(source => {
        const book = SOURCE_BOOK_MAP[source.bookId];
        if (book) {
            const displayTitle = useAbbrev ? book.abbreviation : book.name;
            return source.pageNumber ? `${displayTitle} (pg ${source.pageNumber})` : displayTitle;
        }
        return 'Unknown Source';
    }).join(', ');
}
