
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.11.1
 * Query Engine version: f40f79ec31188888a2e33acda0ecc8fd10a853a9
 */
Prisma.prismaVersion = {
  client: "6.11.1",
  engine: "f40f79ec31188888a2e33acda0ecc8fd10a853a9"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ClassScalarFieldEnum = {
  id: 'id',
  name: 'name',
  abbreviation: 'abbreviation',
  editionId: 'editionId',
  isPrestige: 'isPrestige',
  isVisible: 'isVisible',
  canCastSpells: 'canCastSpells',
  spellsKnown: 'spellsKnown',
  hitDie: 'hitDie',
  description: 'description',
  skillPoints: 'skillPoints',
  castingAbilityId: 'castingAbilityId',
  castingType: 'castingType',
  babProgression: 'babProgression',
  fortProgression: 'fortProgression',
  refProgression: 'refProgression',
  willProgression: 'willProgression'
};

exports.Prisma.SpellcastingProgressionScalarFieldEnum = {
  id: 'id',
  classId: 'classId',
  classLevel: 'classLevel',
  classSpellsKnownId: 'classSpellsKnownId'
};

exports.Prisma.SpellcastingSlotScalarFieldEnum = {
  id: 'id',
  progressionId: 'progressionId',
  spellLevel: 'spellLevel',
  slotsPerDay: 'slotsPerDay'
};

exports.Prisma.SpellcastingLinkScalarFieldEnum = {
  id: 'id',
  featureProgressionId: 'featureProgressionId',
  progressionId: 'progressionId',
  inheritedFrom: 'inheritedFrom',
  levelOffset: 'levelOffset'
};

exports.Prisma.ClassSourceMapScalarFieldEnum = {
  classId: 'classId',
  pageNumber: 'pageNumber',
  sourceBookId: 'sourceBookId'
};

exports.Prisma.SpellLevelMapScalarFieldEnum = {
  classId: 'classId',
  spellId: 'spellId',
  level: 'level',
  isVisible: 'isVisible'
};

exports.Prisma.FeatureScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  description: 'description'
};

exports.Prisma.FeatureProgressionScalarFieldEnum = {
  id: 'id',
  sourceType: 'sourceType',
  level: 'level',
  featureId: 'featureId',
  classId: 'classId',
  raceId: 'raceId'
};

exports.Prisma.FeatureModifierScalarFieldEnum = {
  id: 'id',
  featureProgressionId: 'featureProgressionId',
  type: 'type',
  value: 'value',
  bonusType: 'bonusType',
  appliesTo: 'appliesTo',
  appliesToId: 'appliesToId',
  formulaParamsId: 'formulaParamsId'
};

exports.Prisma.FeatureFormulaParamsScalarFieldEnum = {
  id: 'id',
  formulaId: 'formulaId',
  interval: 'interval',
  formulaStartLevel: 'formulaStartLevel',
  abilityId: 'abilityId',
  thresholds: 'thresholds',
  values: 'values'
};

exports.Prisma.FeatureModifierConditionScalarFieldEnum = {
  id: 'id',
  featureModifierId: 'featureModifierId',
  conditionType: 'conditionType',
  conditionValue: 'conditionValue'
};

exports.Prisma.FeatureSpecialEffectScalarFieldEnum = {
  id: 'id',
  progressionId: 'progressionId',
  effectType: 'effectType',
  key: 'key',
  value: 'value',
  numericValue: 'numericValue',
  featId: 'featId',
  itemId: 'itemId'
};

exports.Prisma.FeatureChoiceScalarFieldEnum = {
  id: 'id',
  progressionId: 'progressionId',
  label: 'label',
  pickCount: 'pickCount',
  type: 'type',
  behavior: 'behavior',
  featId: 'featId',
  featureId: 'featureId',
  formulaParamsId: 'formulaParamsId',
  filterType: 'filterType'
};

exports.Prisma.FeaturePrerequisiteScalarFieldEnum = {
  id: 'id',
  featureId: 'featureId',
  type: 'type',
  skillId: 'skillId',
  minValue: 'minValue'
};

exports.Prisma.SpellScalarFieldEnum = {
  id: 'id',
  name: 'name',
  summary: 'summary',
  description: 'description',
  castingTime: 'castingTime',
  range: 'range',
  rangeTypeId: 'rangeTypeId',
  rangeValue: 'rangeValue',
  area: 'area',
  duration: 'duration',
  savingThrow: 'savingThrow',
  spellResistance: 'spellResistance',
  editionId: 'editionId',
  baseLevel: 'baseLevel',
  effect: 'effect',
  target: 'target'
};

exports.Prisma.SpellDescriptorMapScalarFieldEnum = {
  spellId: 'spellId',
  descriptorId: 'descriptorId'
};

exports.Prisma.SpellSchoolMapScalarFieldEnum = {
  spellId: 'spellId',
  schoolId: 'schoolId'
};

exports.Prisma.SpellSourceMapScalarFieldEnum = {
  spellId: 'spellId',
  sourceBookId: 'sourceBookId',
  pageNumber: 'pageNumber'
};

exports.Prisma.SpellSubschoolMapScalarFieldEnum = {
  spellId: 'spellId',
  subSchoolId: 'subSchoolId'
};

exports.Prisma.SpellComponentMapScalarFieldEnum = {
  spellId: 'spellId',
  componentId: 'componentId'
};

exports.Prisma.SkillScalarFieldEnum = {
  id: 'id',
  name: 'name',
  abilityId: 'abilityId',
  checkDescription: 'checkDescription',
  actionDescription: 'actionDescription',
  retryTypeId: 'retryTypeId',
  retryDescription: 'retryDescription',
  specialNotes: 'specialNotes',
  synergyNotes: 'synergyNotes',
  untrainedNotes: 'untrainedNotes',
  affectedByArmor: 'affectedByArmor',
  description: 'description',
  restrictionNotes: 'restrictionNotes',
  trainedOnly: 'trainedOnly',
  isAnalog: 'isAnalog'
};

exports.Prisma.FeatScalarFieldEnum = {
  id: 'id',
  name: 'name',
  typeId: 'typeId',
  description: 'description',
  benefit: 'benefit',
  normalEffect: 'normalEffect',
  specialEffect: 'specialEffect',
  prerequisites: 'prerequisites',
  repeatable: 'repeatable',
  fighterBonus: 'fighterBonus'
};

exports.Prisma.FeatBenefitMapScalarFieldEnum = {
  featId: 'featId',
  typeId: 'typeId',
  referenceId: 'referenceId',
  amount: 'amount',
  index: 'index'
};

exports.Prisma.FeatPrerequisiteMapScalarFieldEnum = {
  featId: 'featId',
  typeId: 'typeId',
  referenceId: 'referenceId',
  amount: 'amount',
  featureSlug: 'featureSlug',
  index: 'index'
};

exports.Prisma.RaceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  editionId: 'editionId',
  isVisible: 'isVisible',
  description: 'description',
  sizeId: 'sizeId',
  speed: 'speed',
  favoredClassId: 'favoredClassId'
};

exports.Prisma.RaceSourceMapScalarFieldEnum = {
  raceId: 'raceId',
  sourceBookId: 'sourceBookId',
  pageNumber: 'pageNumber'
};

exports.Prisma.ItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  typeId: 'typeId',
  cost: 'cost',
  weight: 'weight',
  quantity: 'quantity'
};

exports.Prisma.ItemTypeScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.ArmorScalarFieldEnum = {
  id: 'id',
  category: 'category',
  bonus: 'bonus',
  dexterityCap: 'dexterityCap',
  checkPenalty: 'checkPenalty',
  arcaneSpellFailure: 'arcaneSpellFailure',
  speedCapThirty: 'speedCapThirty',
  speedCapTwenty: 'speedCapTwenty'
};

exports.Prisma.WeaponScalarFieldEnum = {
  id: 'id',
  category: 'category',
  type: 'type',
  attackBonus: 'attackBonus',
  damageSmall: 'damageSmall',
  damageMedium: 'damageMedium',
  critical: 'critical',
  range: 'range',
  damageType: 'damageType',
  reach: 'reach',
  double: 'double',
  nonlethal: 'nonlethal'
};

exports.Prisma.ItemPropertyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  flatCostModifier: 'flatCostModifier',
  costMultiplier: 'costMultiplier',
  costFormula: 'costFormula',
  enhancementBonusValue: 'enhancementBonusValue',
  bonusEquivalentModifier: 'bonusEquivalentModifier',
  exclusiveMaterial: 'exclusiveMaterial'
};

exports.Prisma.ItemPropertyAppliesToScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  itemType: 'itemType'
};

exports.Prisma.ItemPropertyIncompatibilityScalarFieldEnum = {
  id: 'id',
  propertyAId: 'propertyAId',
  propertyBId: 'propertyBId'
};

exports.Prisma.ItemTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  itemId: 'itemId'
};

exports.Prisma.ItemTemplatePropertyScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  propertyId: 'propertyId'
};

exports.Prisma.CharacterItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  quantity: 'quantity',
  characterId: 'characterId',
  baseItemId: 'baseItemId'
};

exports.Prisma.CharacterItemPropertyScalarFieldEnum = {
  id: 'id',
  characterItemId: 'characterItemId',
  propertyId: 'propertyId'
};

exports.Prisma.SourceBookScalarFieldEnum = {
  id: 'id',
  name: 'name',
  abbreviation: 'abbreviation',
  releaseDate: 'releaseDate',
  editionId: 'editionId',
  description: 'description',
  isVisible: 'isVisible'
};

exports.Prisma.ReferenceTableScalarFieldEnum = {
  slug: 'slug',
  name: 'name',
  description: 'description'
};

exports.Prisma.ReferenceTableColumnScalarFieldEnum = {
  tableSlug: 'tableSlug',
  index: 'index',
  header: 'header',
  span: 'span',
  alignment: 'alignment'
};

exports.Prisma.ReferenceTableRowScalarFieldEnum = {
  tableSlug: 'tableSlug',
  index: 'index'
};

exports.Prisma.ReferenceTableCellScalarFieldEnum = {
  tableSlug: 'tableSlug',
  columnIndex: 'columnIndex',
  rowIndex: 'rowIndex',
  value: 'value',
  colSpan: 'colSpan',
  rowSpan: 'rowSpan'
};

exports.Prisma.UserCharacterScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  raceId: 'raceId',
  alignmentId: 'alignmentId',
  xp: 'xp',
  age: 'age',
  height: 'height',
  weight: 'weight',
  eyes: 'eyes',
  hair: 'hair',
  gender: 'gender',
  notes: 'notes'
};

exports.Prisma.UserCharacterAbilityScoreScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  abilityId: 'abilityId',
  value: 'value'
};

exports.Prisma.CharacterAdvancementScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  level: 'level',
  version: 'version',
  classId: 'classId',
  secondaryClassId: 'secondaryClassId',
  hitPoints: 'hitPoints',
  abilityId: 'abilityId',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.AdvancementSkillScalarFieldEnum = {
  advancementId: 'advancementId',
  skillId: 'skillId',
  pointsSpent: 'pointsSpent'
};

exports.Prisma.AdvancementFeatScalarFieldEnum = {
  advancementId: 'advancementId',
  featId: 'featId'
};

exports.Prisma.AdvancementSpellScalarFieldEnum = {
  advancementId: 'advancementId',
  spellId: 'spellId'
};

exports.Prisma.CharacterFeatureChoiceScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  featureChoiceId: 'featureChoiceId',
  progressionId: 'progressionId',
  advancementId: 'advancementId',
  key: 'key',
  value: 'value',
  choiceIndex: 'choiceIndex'
};

exports.Prisma.CharacterSpellPreparationScalarFieldEnum = {
  characterId: 'characterId',
  classId: 'classId',
  spellId: 'spellId',
  spellLevel: 'spellLevel',
  quantity: 'quantity',
  prepKey: 'prepKey',
  slotType: 'slotType'
};

exports.Prisma.SpellPreparationMetamagicScalarFieldEnum = {
  characterId: 'characterId',
  prepKey: 'prepKey',
  featId: 'featId'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  isAdmin: 'isAdmin',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  preferredEditionId: 'preferredEditionId',
  diceConfigBase: 'diceConfigBase'
};

exports.Prisma.DiceBoxAdminConfigScalarFieldEnum = {
  id: 'id',
  name: 'name',
  isDefault: 'isDefault',
  gravity: 'gravity',
  mass: 'mass',
  friction: 'friction',
  restitution: 'restitution',
  angularDamping: 'angularDamping',
  linearDamping: 'linearDamping',
  spinForce: 'spinForce',
  throwForce: 'throwForce',
  startingHeight: 'startingHeight',
  settleTimeout: 'settleTimeout',
  lightIntensity: 'lightIntensity',
  enableShadows: 'enableShadows',
  shadowTransparency: 'shadowTransparency',
  theme: 'theme',
  themeColor: 'themeColor',
  iconColor: 'iconColor',
  scale: 'scale',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserDiceConfigOverrideScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  propertyName: 'propertyName',
  propertyValue: 'propertyValue'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.ClassOrderByRelevanceFieldEnum = {
  name: 'name',
  abbreviation: 'abbreviation',
  description: 'description'
};

exports.Prisma.SpellcastingLinkOrderByRelevanceFieldEnum = {
  inheritedFrom: 'inheritedFrom'
};

exports.Prisma.FeatureOrderByRelevanceFieldEnum = {
  slug: 'slug',
  name: 'name',
  description: 'description'
};

exports.Prisma.FeatureFormulaParamsOrderByRelevanceFieldEnum = {
  thresholds: 'thresholds',
  values: 'values'
};

exports.Prisma.FeatureSpecialEffectOrderByRelevanceFieldEnum = {
  key: 'key',
  value: 'value'
};

exports.Prisma.FeatureChoiceOrderByRelevanceFieldEnum = {
  label: 'label'
};

exports.Prisma.SpellOrderByRelevanceFieldEnum = {
  name: 'name',
  summary: 'summary',
  description: 'description',
  castingTime: 'castingTime',
  range: 'range',
  rangeValue: 'rangeValue',
  area: 'area',
  duration: 'duration',
  savingThrow: 'savingThrow',
  spellResistance: 'spellResistance',
  effect: 'effect',
  target: 'target'
};

exports.Prisma.SkillOrderByRelevanceFieldEnum = {
  name: 'name',
  checkDescription: 'checkDescription',
  actionDescription: 'actionDescription',
  retryDescription: 'retryDescription',
  specialNotes: 'specialNotes',
  synergyNotes: 'synergyNotes',
  untrainedNotes: 'untrainedNotes',
  description: 'description',
  restrictionNotes: 'restrictionNotes'
};

exports.Prisma.FeatOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description',
  benefit: 'benefit',
  normalEffect: 'normalEffect',
  specialEffect: 'specialEffect',
  prerequisites: 'prerequisites'
};

exports.Prisma.FeatPrerequisiteMapOrderByRelevanceFieldEnum = {
  featureSlug: 'featureSlug'
};

exports.Prisma.RaceOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
};

exports.Prisma.ItemOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description'
};

exports.Prisma.ItemTypeOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.WeaponOrderByRelevanceFieldEnum = {
  damageSmall: 'damageSmall',
  damageMedium: 'damageMedium',
  critical: 'critical',
  range: 'range',
  damageType: 'damageType'
};

exports.Prisma.ItemPropertyOrderByRelevanceFieldEnum = {
  name: 'name',
  costFormula: 'costFormula'
};

exports.Prisma.ItemTemplateOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.CharacterItemOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.SourceBookOrderByRelevanceFieldEnum = {
  name: 'name',
  abbreviation: 'abbreviation',
  description: 'description'
};

exports.Prisma.ReferenceTableOrderByRelevanceFieldEnum = {
  slug: 'slug',
  name: 'name',
  description: 'description'
};

exports.Prisma.ReferenceTableColumnOrderByRelevanceFieldEnum = {
  tableSlug: 'tableSlug',
  header: 'header'
};

exports.Prisma.ReferenceTableRowOrderByRelevanceFieldEnum = {
  tableSlug: 'tableSlug'
};

exports.Prisma.ReferenceTableCellOrderByRelevanceFieldEnum = {
  tableSlug: 'tableSlug',
  value: 'value'
};

exports.Prisma.UserCharacterOrderByRelevanceFieldEnum = {
  name: 'name',
  eyes: 'eyes',
  hair: 'hair',
  gender: 'gender',
  notes: 'notes'
};

exports.Prisma.CharacterAdvancementOrderByRelevanceFieldEnum = {
  notes: 'notes'
};

exports.Prisma.CharacterFeatureChoiceOrderByRelevanceFieldEnum = {
  key: 'key',
  value: 'value'
};

exports.Prisma.CharacterSpellPreparationOrderByRelevanceFieldEnum = {
  prepKey: 'prepKey'
};

exports.Prisma.SpellPreparationMetamagicOrderByRelevanceFieldEnum = {
  prepKey: 'prepKey'
};

exports.Prisma.UserOrderByRelevanceFieldEnum = {
  username: 'username',
  email: 'email',
  password: 'password'
};

exports.Prisma.DiceBoxAdminConfigOrderByRelevanceFieldEnum = {
  name: 'name',
  themeColor: 'themeColor',
  iconColor: 'iconColor'
};

exports.Prisma.UserDiceConfigOverrideOrderByRelevanceFieldEnum = {
  propertyName: 'propertyName',
  propertyValue: 'propertyValue'
};
exports.ItemPropertyType = exports.$Enums.ItemPropertyType = {
  Material: 'Material',
  Enhancement: 'Enhancement',
  SpecialAbility: 'SpecialAbility',
  Structural: 'Structural'
};

exports.ItemApplicableTypeEnum = exports.$Enums.ItemApplicableTypeEnum = {
  Weapon: 'Weapon',
  Armor: 'Armor',
  Shield: 'Shield',
  MountArmor: 'MountArmor',
  Ammunition: 'Ammunition'
};

exports.TextAlignment = exports.$Enums.TextAlignment = {
  left: 'left',
  center: 'center',
  right: 'right'
};

exports.Prisma.ModelName = {
  Class: 'Class',
  SpellcastingProgression: 'SpellcastingProgression',
  SpellcastingSlot: 'SpellcastingSlot',
  SpellcastingLink: 'SpellcastingLink',
  ClassSourceMap: 'ClassSourceMap',
  SpellLevelMap: 'SpellLevelMap',
  Feature: 'Feature',
  FeatureProgression: 'FeatureProgression',
  FeatureModifier: 'FeatureModifier',
  FeatureFormulaParams: 'FeatureFormulaParams',
  FeatureModifierCondition: 'FeatureModifierCondition',
  FeatureSpecialEffect: 'FeatureSpecialEffect',
  FeatureChoice: 'FeatureChoice',
  FeaturePrerequisite: 'FeaturePrerequisite',
  Spell: 'Spell',
  SpellDescriptorMap: 'SpellDescriptorMap',
  SpellSchoolMap: 'SpellSchoolMap',
  SpellSourceMap: 'SpellSourceMap',
  SpellSubschoolMap: 'SpellSubschoolMap',
  SpellComponentMap: 'SpellComponentMap',
  Skill: 'Skill',
  Feat: 'Feat',
  FeatBenefitMap: 'FeatBenefitMap',
  FeatPrerequisiteMap: 'FeatPrerequisiteMap',
  Race: 'Race',
  RaceSourceMap: 'RaceSourceMap',
  Item: 'Item',
  ItemType: 'ItemType',
  Armor: 'Armor',
  Weapon: 'Weapon',
  ItemProperty: 'ItemProperty',
  ItemPropertyAppliesTo: 'ItemPropertyAppliesTo',
  ItemPropertyIncompatibility: 'ItemPropertyIncompatibility',
  ItemTemplate: 'ItemTemplate',
  ItemTemplateProperty: 'ItemTemplateProperty',
  CharacterItem: 'CharacterItem',
  CharacterItemProperty: 'CharacterItemProperty',
  SourceBook: 'SourceBook',
  ReferenceTable: 'ReferenceTable',
  ReferenceTableColumn: 'ReferenceTableColumn',
  ReferenceTableRow: 'ReferenceTableRow',
  ReferenceTableCell: 'ReferenceTableCell',
  UserCharacter: 'UserCharacter',
  UserCharacterAbilityScore: 'UserCharacterAbilityScore',
  CharacterAdvancement: 'CharacterAdvancement',
  AdvancementSkill: 'AdvancementSkill',
  AdvancementFeat: 'AdvancementFeat',
  AdvancementSpell: 'AdvancementSpell',
  CharacterFeatureChoice: 'CharacterFeatureChoice',
  CharacterSpellPreparation: 'CharacterSpellPreparation',
  SpellPreparationMetamagic: 'SpellPreparationMetamagic',
  User: 'User',
  DiceBoxAdminConfig: 'DiceBoxAdminConfig',
  UserDiceConfigOverride: 'UserDiceConfigOverride'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
