/**
 * Utility functions for transforming formula parameters between string/array format.
 * 
 * This module handles the transformation between database storage format (comma-separated
 * strings) and application format (arrays) for formula parameters. Formula parameters
 * include thresholds and values used in feature calculations.
 * 
 * Architecture Decisions:
 * - Database storage: Comma-separated strings are used in the database for simplicity
 *   and compatibility with Prisma's string type
 * - Application format: Arrays are used in application logic for easier manipulation,
 *   validation, and type safety
 * - Transformation layer: Separate transformer functions ensure clean separation between
 *   database and application concerns
 * - Dice notation support: Values can contain dice notation (e.g., "1d6") which must
 *   remain as strings, while numeric values are parsed to numbers
 * 
 * Usage Pattern:
 * - When reading from database: Use transformFormulaParamsFromDatabase()
 * - When writing to database: Use transformFormulaParamsForDatabase() or
 *   transformFormulaParamsForDatabaseCreate()
 * 
 * Source File: `apps/backend/src/utils/formulaParamTransformers.ts`
 */

import { Prisma } from '@shared/prisma-client';
import { CreateFeatureFormulaParamsRequest, FeatureFormulaParams } from '@shared/schema';

/**
 * Transforms formula parameters from application format (arrays) to database format (strings).
 * 
 * Converts thresholds and values arrays to comma-separated strings for database storage.
 * Used when updating existing formula parameters in the database.
 * 
 * Architecture Decision: Separate update and create transformers allow for different
 * Prisma input types (UpdateInput vs CreateInput), ensuring type safety.
 * 
 * @param formulaParams - Formula parameters in application format (arrays)
 * @returns Formula parameters in database format (comma-separated strings)
 * 
 * @example
 * ```typescript
 * const dbParams = transformFormulaParamsForDatabase({
 *   thresholds: [1, 5, 10],
 *   values: [2, 4, 6]
 * });
 * // dbParams.thresholds = "1,5,10"
 * // dbParams.values = "2,4,6"
 * ```
 */
export function transformFormulaParamsForDatabase(formulaParams: FeatureFormulaParams): Prisma.FeatureFormulaParamsUpdateInput {
    return {
        ...formulaParams,
        // Transform arrays to comma-separated strings
        thresholds: formulaParams.thresholds ? formulaParams.thresholds.join(',') : null,
        values: formulaParams.values ? formulaParams.values.map(v => String(v)).join(',') : null,
    };
}

/**
 * Transforms formula parameters from application format to database format for create operations.
 * 
 * Similar to transformFormulaParamsForDatabase but uses CreateInput type which omits
 * the id field (generated by database).
 * 
 * @param formulaParams - Formula parameters in application format (arrays)
 * @returns Formula parameters in database format (comma-separated strings) for creation
 * 
 * @example
 * ```typescript
 * const dbParams = transformFormulaParamsForDatabaseCreate({
 *   thresholds: [1, 5, 10],
 *   values: [2, 4, 6]
 * });
 * await prisma.featureFormulaParams.create({ data: dbParams });
 * ```
 */
export function transformFormulaParamsForDatabaseCreate(formulaParams: CreateFeatureFormulaParamsRequest): Prisma.FeatureFormulaParamsCreateInput {
    return {
        ...formulaParams,
        // Transform arrays to comma-separated strings
        thresholds: formulaParams.thresholds ? formulaParams.thresholds.join(',') : null,
        values: formulaParams.values ? formulaParams.values.map(v => String(v)).join(',') : null,
    };
}

/**
 * Transforms formula parameters from database format (strings) to application format (arrays).
 * 
 * Converts comma-separated strings from the database to arrays for use in application logic.
 * Handles both numeric values and dice notation strings (e.g., "1d6").
 * 
 * Architecture Decision: Dice notation detection (checking for 'd' character) allows
 * the system to preserve dice strings while parsing numeric values, maintaining
 * flexibility for D&D mechanics.
 * 
 * @param formulaParams - Formula parameters from database (comma-separated strings)
 * @returns Formula parameters in application format (arrays with numbers and strings)
 * 
 * @example
 * ```typescript
 * const dbParams = await prisma.featureFormulaParams.findUnique({ where: { id } });
 * const appParams = transformFormulaParamsFromDatabase(dbParams);
 * // appParams.thresholds = [1, 5, 10]
 * // appParams.values = [2, 4, "1d6"]
 * ```
 */
export function transformFormulaParamsFromDatabase(formulaParams: Prisma.FeatureFormulaParamsGetPayload<object>): FeatureFormulaParams {
    return {
        ...formulaParams,
        // Transform comma-separated strings to arrays
        thresholds: formulaParams.thresholds
            ? formulaParams.thresholds.split(',').map(s => parseInt(s.trim(), 10))
            : null,
        values: formulaParams.values
            ? formulaParams.values.split(',').map(s => {
                const trimmed = s.trim();
                // Check if it's a dice notation (contains 'd')
                if (trimmed.includes('d')) {
                    return trimmed; // Keep as string for dice notation
                }
                // Try to parse as number for non-dice values
                const num = parseInt(trimmed, 10);
                return isNaN(num) ? trimmed : num;
            })
            : null,
        // Cast valuesRepresent to the proper enum type
        valuesRepresent: formulaParams.valuesRepresent as FeatureFormulaParams['valuesRepresent'],
    };
}

/**
 * Validates that thresholds and values arrays have compatible lengths.
 * 
 * For conditional scaling formulas, thresholds and values must have the same length
 * to properly map threshold ranges to values. This function ensures data integrity.
 * 
 * Architecture Decision: Both arrays can be null/undefined independently, but if both
 * are provided, they must have matching lengths for the formula to be valid.
 * 
 * @param thresholds - Array of threshold values (optional)
 * @param values - Array of values corresponding to thresholds (optional)
 * @returns True if arrays are compatible (both null, or both have same length)
 * 
 * @example
 * ```typescript
 * if (!validateThresholdsAndValues(thresholds, values)) {
 *   throw new Error('Thresholds and values must have the same length');
 * }
 * ```
 */
export function validateThresholdsAndValues(thresholds?: number[] | null, values?: (string | number)[] | null): boolean {
    if (!thresholds || !values) {
        return true; // Both can be null/undefined
    }

    // For conditional scaling, thresholds and values should have the same length
    return thresholds.length === values.length;
}

/**
 * Parses a comma-separated string into an array of numbers and strings.
 * 
 * Legacy function maintained for backward compatibility. Attempts to parse each
 * segment as a number, falling back to string if parsing fails.
 * 
 * Architecture Decision: Maintained for backward compatibility with older code
 * that may still use this format directly.
 * 
 * @param input - Comma-separated string to parse
 * @returns Array of parsed values (numbers where possible, strings otherwise), or null
 * 
 * @example
 * ```typescript
 * const values = parseCommaSeparatedString("1,2,3,1d6");
 * // values = [1, 2, 3, "1d6"]
 * ```
 */
export function parseCommaSeparatedString(input: string | null | undefined): (string | number)[] | null {
    if (!input) {
        return null;
    }

    return input.split(',').map(s => {
        const trimmed = s.trim();
        const num = parseInt(trimmed, 10);
        return isNaN(num) ? trimmed : num;
    });
}

/**
 * Converts an array of numbers and strings to a comma-separated string.
 * 
 * Legacy function maintained for backward compatibility. Converts all values
 * to strings and joins with commas.
 * 
 * @param input - Array of values to convert
 * @returns Comma-separated string, or null if input is null/undefined/empty
 * 
 * @example
 * ```typescript
 * const str = arrayToCommaSeparatedString([1, 2, 3, "1d6"]);
 * // str = "1,2,3,1d6"
 * ```
 */
export function arrayToCommaSeparatedString(input: (string | number)[] | null | undefined): string | null {
    if (!input || input.length === 0) {
        return null;
    }

    return input.map(v => String(v)).join(',');
}
